"""The explicit record, not the clean upload that looks exactly like it.

YouTube's auto-generated uploads of a clean and an explicit release share a
title, an album name and the "Provided to YouTube by" description. Only
YouTube Music's explicit flag tells them apart. No network: every YouTube
Music answer here is fabricated in the shape radio.ytmusic returns, modelled
on songs that really aired clean (Sugar, Cinderella, MOOO!, family ties).
"""
import tempfile
import threading
import unittest
from pathlib import Path
from unittest.mock import patch

from radio import config, db, editions, library, sourceio, versions, ytmusic

ART = "Provided to YouTube by Label\n\nSong · Artist\n\nAuto-generated by YouTube."


def song(video_id, title, artists, album, duration, explicit, video_type=ytmusic.ATV):
    return {"video_id": video_id, "title": title, "artists": artists, "album": album,
            "duration": duration, "explicit": explicit, "video_type": video_type}


SUGAR = [song("MozAXGgC1Mc", "Sugar", ["Maroon 5"], "V (Deluxe)", 236, True),
         song("YSWrmX4_qFA", "Animals", ["Maroon 5"], "V", 231, False),
         song("iPcX6EpJI3o", "Sugar", ["Maroon 5"], "V", 236, False),
         song("slowed00001", "Sugar (Slowed + Reverb)", ["Maroon 5"], "Sugar (Slowed + Reverb)", 280, True),
         song("spedup00001", "Sugar", ["Maroon 5"], "Sugar (Sped Up)", 190, True),
         song("mvideo00001", "Sugar", ["Maroon 5"], "", 301, True, "MUSIC_VIDEO_TYPE_OMV")]
FAMILY_TIES = [song("FTclean0001", "family ties", ["Baby Keem", "Kendrick Lamar"], "The Melodic Blue", 252, False),
               song("FTexplct001", "family ties", ["Baby Keem", "Kendrick Lamar"], "The Melodic Blue", 252, True),
               song("FTother0001", "trademark usa", ["Baby Keem"], "The Melodic Blue", 276, True)]
CINDERELLA = [song("wbt_E7LNDaA", "Cinderella (feat. Ty Dolla $ign)", ["Mac Miller"], "The Divine Feminine", 481, True),
              song("XVhqcmyne2A", "My Favorite Part", ["Mac Miller", "Ariana Grande"], "The Divine Feminine", 216, False)]
NO_EXPLICIT = [song("clean000001", "Song", ["Artist"], "Record", 200, False),
               song("clean000002", "Song", ["Artist"], "Record (Deluxe)", 201, False)]


def upload(video_id, title, duration=236, description=ART, channel=""):
    return {"id": video_id, "title": title, "duration": duration, "description": description,
            "channel": channel}


class YouTubeMusicTest(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.root = Path(temp.name)
        self.settings = {}
        self.answers = {}      # query or video id -> fabricated answer
        self.calls = []
        for patcher in (patch.object(config, "CACHE_DIR", self.root),
                        patch.object(config.station, "get", side_effect=lambda k, d=None: self.settings.get(k, d)),
                        patch.object(library, "_source_info", return_value={}),
                        patch.object(ytmusic, "MIN_GAP", 0),
                        patch.object(sourceio, "ytmusic", side_effect=self.youtube_music)):
            patcher.start()
            self.addCleanup(patcher.stop)
        ytmusic._reset()
        self.addCleanup(ytmusic._reset)

    def youtube_music(self, payload):
        self.calls.append(payload)
        answer = self.answers.get(payload.get("query") or payload.get("video_id"))
        if isinstance(answer, Exception):
            raise answer
        if answer is None:
            return [] if payload["op"] == "songs" else {}
        return answer


class TestResolverPrefersTheExplicitRelease(YouTubeMusicTest):
    def test_explicit_sibling_beats_the_clean_auto_generated_upload(self):
        """Sugar aired from the clean album's upload: same title, same length."""
        self.answers["Maroon 5 Sugar"] = SUGAR
        with patch.object(library.sourceio, "search",
                          return_value={"entries": [upload("iPcX6EpJI3o", "Sugar")]}) as search:
            self.assertEqual(library.resolve("Maroon 5", "Sugar", 236000), "MozAXGgC1Mc")
            # YouTube Music answered, so no second, title-only search.
            self.assertEqual(search.call_count, 1)
        self.assertTrue(library._edition_checked("MozAXGgC1Mc", "Maroon 5", "Sugar"))

    def test_family_ties_regression(self):
        self.answers["Baby Keem family ties"] = FAMILY_TIES
        entries = [upload("FTclean0001", "family ties", 252), upload("FTother0001", "trademark usa", 276)]
        with patch.object(library.sourceio, "search", return_value={"entries": entries}):
            self.assertEqual(library.resolve("Baby Keem & Kendrick Lamar", "family ties", 252000), "FTexplct001")

    def test_featured_credits_do_not_hide_the_match(self):
        self.answers["Mac Miller Cinderella"] = CINDERELLA
        with patch.object(library.sourceio, "search",
                          return_value={"entries": [upload("HCgltcEaB_0", "Cinderella", 480)]}):
            self.assertEqual(library.resolve("Mac Miller", "Cinderella", 480000), "wbt_E7LNDaA")

    def test_song_without_an_explicit_version_keeps_the_normal_pick(self):
        self.answers["Artist Song"] = NO_EXPLICIT
        with patch.object(library.sourceio, "search",
                          return_value={"entries": [upload("clean000001", "Artist - Song", 200)]}) as search:
            self.assertEqual(library.resolve("Artist", "Song", 200000), "clean000001")
            self.assertEqual(search.call_count, 1)
        self.assertTrue(library._edition_checked("clean000001", "Artist", "Song"))

    def test_alternate_takes_and_music_videos_are_not_preferred(self):
        self.answers["Maroon 5 Sugar"] = [s for s in SUGAR if s["video_id"] != "MozAXGgC1Mc"]
        with patch.object(library.sourceio, "search",
                          return_value={"entries": [upload("iPcX6EpJI3o", "Sugar")]}):
            self.assertEqual(library.resolve("Maroon 5", "Sugar", 236000), "iPcX6EpJI3o")
        self.assertEqual(ytmusic.matches(SUGAR, "Maroon 5", "Sugar"),
                         [SUGAR[0], SUGAR[2]])
        # Unless that take is the one asked for.
        self.assertIn(SUGAR[3], ytmusic.matches(SUGAR, "Maroon 5", "Sugar (Slowed + Reverb)"))

    def test_other_artists_and_other_lengths_are_not_the_record(self):
        found = [song("cover000001", "Sugar", ["Someone Else"], "Covers", 236, True),
                 song("extended001", "Sugar", ["Maroon 5"], "Other Record", 330, True),
                 SUGAR[2]]
        self.assertEqual(ytmusic.matches(found, "Maroon 5", "Sugar"), [found[1], found[2]])
        # Spelling of one credit is not another artist.
        for artist, credit in (("ROSE", "ROSÉ"), ("BORNS", "BØRNS"), ("Run-D.M.C.", "RUN DMC")):
            self.assertEqual(len(ytmusic.matches([song("abcdefghijk", "Song", [credit], "", 200, True)],
                                                 artist, "Song")), 1, artist)
        self.answers["Maroon 5 Sugar"] = found
        self.assertEqual(ytmusic.explicit_choice("Maroon 5", "Sugar", 236000)["explicit"], [])

    def test_clean_request_is_honoured_without_asking(self):
        with patch.object(library.sourceio, "search",
                          return_value={"entries": [upload("iPcX6EpJI3o", "Maroon 5 - Sugar (Clean)")]}):
            self.assertEqual(library.resolve("Maroon 5", "Sugar (Clean)"), "iPcX6EpJI3o")
        self.assertEqual(self.calls, [])

    def test_preference_off_asks_nothing(self):
        self.settings["selection.avoid_clean_versions"] = False
        with patch.object(library.sourceio, "search",
                          return_value={"entries": [upload("iPcX6EpJI3o", "Sugar")]}):
            self.assertEqual(library.resolve("Maroon 5", "Sugar", 236000), "iPcX6EpJI3o")
        self.assertEqual(self.calls, [])

    def test_exact_links_stay_pinned(self):
        with patch.object(library, "resolve") as resolve, \
             patch.object(library, "_download_raw", return_value=self.root / "raw.webm"):
            self.assertEqual(library.fetch_recording("Maroon 5", "Sugar", video_id="iPcX6EpJI3o",
                                                     pinned=True)[0], "iPcX6EpJI3o")
        resolve.assert_not_called()
        self.assertEqual(self.calls, [])

    def test_network_failure_falls_back_and_cools_down(self):
        self.answers["Maroon 5 Sugar"] = sourceio.SourceError("timed out")
        with patch.object(library.sourceio, "search",
                          return_value={"entries": [upload("iPcX6EpJI3o", "Sugar")]}) as search:
            self.assertEqual(library.resolve("Maroon 5", "Sugar", 236000), "iPcX6EpJI3o")
            self.assertEqual(search.call_count, 2)  # today's title-only explicit search
            self.assertEqual(library.resolve("Maroon 5", "Sugar", 236000), "iPcX6EpJI3o")
        self.assertEqual(len(self.calls), 1)  # the failure is remembered
        # A text-only answer is looked at again much sooner than a flagged one.
        with patch.object(library.time, "time", return_value=library.time.time() + 7 * 3600):
            self.assertFalse(library._edition_checked("iPcX6EpJI3o", "Maroon 5", "Sugar"))

    def test_an_unavailable_explicit_upload_falls_back_to_one_that_plays(self):
        self.answers["Maroon 5 Sugar"] = SUGAR
        with patch.object(library.sourceio, "search",
                          return_value={"entries": [upload("iPcX6EpJI3o", "Maroon 5 - Sugar")]}):
            self.assertEqual(library.resolve("Maroon 5", "Sugar", 236000, exclude={"MozAXGgC1Mc"}),
                             "iPcX6EpJI3o")


class TestLookupCache(YouTubeMusicTest):
    def test_answers_are_cached_on_disk(self):
        self.answers["Maroon 5 Sugar"] = SUGAR
        self.assertEqual(ytmusic.songs("Maroon 5", "Sugar"), SUGAR)
        ytmusic._reset()
        self.assertEqual(ytmusic.songs("Maroon 5", "Sugar"), SUGAR)
        self.assertEqual(len(self.calls), 1)
        later = ytmusic.time.time() + ytmusic.TTL + 1
        with patch.object(ytmusic.time, "time", return_value=later):
            ytmusic.songs("Maroon 5", "Sugar")
        self.assertEqual(len(self.calls), 2)

    def test_not_found_is_cached_for_less_time(self):
        self.assertEqual(ytmusic.songs("Nobody", "Nothing"), [])
        later = ytmusic.time.time() + ytmusic.EMPTY_TTL + 1
        with patch.object(ytmusic.time, "time", return_value=later):
            ytmusic.songs("Nobody", "Nothing")
        self.assertEqual(len(self.calls), 2)

    def test_failures_pause_lookups_then_retry(self):
        self.answers["Maroon 5 Sugar"] = sourceio.SourceError("offline")
        self.assertIsNone(ytmusic.songs("Maroon 5", "Sugar"))
        self.assertIsNone(ytmusic.songs("Doja Cat", "MOOO!"))  # paused for everything
        self.assertEqual(len(self.calls), 1)
        self.assertFalse(list((self.root / "source-info").rglob("*.json")))  # never on disk
        self.answers["Maroon 5 Sugar"] = SUGAR
        now = ytmusic.time.monotonic()
        with patch.object(ytmusic.time, "monotonic", return_value=now + ytmusic.OUTAGE_PAUSE + 1):
            self.assertIsNone(ytmusic.songs("Maroon 5", "Sugar"))  # that lookup cools down longer
            self.assertEqual(ytmusic.songs("Doja Cat", "MOOO!"), [])
        with patch.object(ytmusic.time, "monotonic", return_value=now + ytmusic.FAILURE_COOLDOWN + 1):
            self.assertEqual(ytmusic.songs("Maroon 5", "Sugar"), SUGAR)

    def test_malformed_answers_count_as_failures(self):
        self.answers["Maroon 5 Sugar"] = {"not": "a list"}
        self.assertIsNone(ytmusic.songs("Maroon 5", "Sugar"))
        self.assertEqual(ytmusic._song({"videoId": "bad"}), None)

    def test_child_side_reads_flags_and_album_editions(self):
        class Client:
            def search(self, query, filter, limit):
                return [{"videoId": "MozAXGgC1Mc", "title": "Sugar", "artists": [{"name": "Maroon 5"}],
                         "album": {"name": "V (Deluxe)"}, "duration_seconds": 236, "isExplicit": True,
                         "videoType": ytmusic.ATV}, {"videoId": None}]

            def get_watch_playlist(self, videoId, limit):
                return {"tracks": [{"videoId": videoId, "title": "Cinderella (feat. Ty Dolla $ign)",
                                    "artists": [{"name": "Mac Miller"}], "length": "8:01",
                                    "album": {"name": "The Divine Feminine", "id": "MPREb_clean"},
                                    "isExplicit": None, "videoType": ytmusic.ATV}]}

            def get_album(self, browse_id):
                return {"isExplicit": False, "tracks": [
                    {"title": "Cinderella (feat. Ty Dolla $ign)", "isExplicit": False}]}

        import types
        fake = types.SimpleNamespace(YTMusic=Client)
        with patch.dict("sys.modules", {"ytmusicapi": fake}):
            found = ytmusic.fetch({"op": "songs", "query": "Maroon 5 Sugar"})
            upload_ = ytmusic.fetch({"op": "edition", "video_id": "HCgltcEaB_0"})
        self.assertEqual(found, [song("MozAXGgC1Mc", "Sugar", ["Maroon 5"], "V (Deluxe)", 236, True)])
        self.assertEqual((upload_["explicit"], upload_["duration"]), (False, 481))


class TestVerdict(YouTubeMusicTest):
    def test_clean_upload_with_explicit_sibling(self):
        self.answers["Maroon 5 Sugar"] = SUGAR
        found = ytmusic.verdict("iPcX6EpJI3o", "Maroon 5", "Sugar", 236)
        self.assertEqual((found["status"], found["upgrade"]), ("upgrade", "MozAXGgC1Mc"))

    def test_flag_read_from_the_album_when_search_misses_the_upload(self):
        self.answers["Mac Miller Cinderella"] = CINDERELLA
        self.answers["HCgltcEaB_0"] = song("HCgltcEaB_0", "Cinderella (feat. Ty Dolla $ign)", ["Mac Miller"],
                                           "The Divine Feminine", 481, False)
        found = ytmusic.verdict("HCgltcEaB_0", "Mac Miller", "Cinderella", 480)
        self.assertEqual((found["status"], found["upgrade"]), ("upgrade", "wbt_E7LNDaA"))

    def test_a_re_upload_without_a_flag_gives_way_to_the_explicit_release(self):
        """family ties aired from somebody's "(Official Audio)" re-upload."""
        self.answers["Baby Keem family ties"] = FAMILY_TIES
        self.answers["JBMYErFC6Wo"] = song("JBMYErFC6Wo", "Baby Keem & Kendrick Lamar - Family Ties (Official Audio)",
                                           ["Some Uploader"], "", 253, None, "MUSIC_VIDEO_TYPE_UGC")
        found = ytmusic.verdict("JBMYErFC6Wo", "Baby Keem", "family ties", 252.11)
        self.assertEqual((found["status"], found["upgrade"]), ("upgrade", "FTexplct001"))

    def test_other_answers(self):
        self.answers["Maroon 5 Sugar"] = SUGAR
        self.assertEqual(ytmusic.verdict("MozAXGgC1Mc", "Maroon 5", "Sugar", 236)["status"], "explicit")
        self.answers["Artist Song"] = NO_EXPLICIT
        self.assertEqual(ytmusic.verdict("clean000001", "Artist", "Song", 200)["status"], "no-explicit-version")
        self.assertEqual(ytmusic.verdict("abcdefghijk", "Nobody", "Nothing", 200)["status"], "not-found")
        # An upload whose own flag cannot be read is not swapped on a guess.
        self.assertEqual(ytmusic.verdict("officialaud", "Maroon 5", "Sugar", 236)["status"], "unknown")


class CachedBase(YouTubeMusicTest):
    def setUp(self):
        super().setUp()
        self.local = threading.local()
        for patcher in (patch.object(db, "_DB_PATH", self.root / "test.db"),
                        patch.object(db, "_LOCAL", self.local)):
            patcher.start()
            self.addCleanup(patcher.stop)
        self.addCleanup(lambda: getattr(self.local, "conn", None) and self.local.conn.close())
        db.connect()
        self.answers["Maroon 5 Sugar"] = SUGAR
        self.answers["Artist Song"] = NO_EXPLICIT
        self.answers["Doja Cat MOOO!"] = [
            song("5wIeHP6dscU", "MOOO!", ["Doja Cat"], "Amala (Deluxe Version)", 286, True)]

    def cache(self, key, artist, title, video_id, **extra):
        path = self.root / f"{key}.opus"
        path.write_bytes(b"working audio")
        values = {"key": key, "artist": artist, "title": title, "video_id": video_id, "file": str(path),
                  "duration": 236, "added_at": 0, "source": "seed", **extra}
        db.write(f"INSERT INTO tracks({','.join(values)}) VALUES ({','.join('?' * len(values))})",
                 tuple(values.values()))
        return path


class TestCachedRecheck(CachedBase):
    def test_swap_scheduled_only_when_an_explicit_sibling_exists(self):
        self.cache("sugar", "Maroon 5", "Sugar", "iPcX6EpJI3o", play_count=5)
        self.cache("song", "Artist", "Song", "clean000001", duration=200, play_count=4)
        self.cache("explicit", "Maroon 5", "Sugar", "MozAXGgC1Mc", play_count=3)
        with patch.object(library, "upgrade", return_value=True) as upgrade:
            results = editions.run_batch(10, protect=lambda: set())
        upgrade.assert_called_once()
        self.assertEqual(upgrade.call_args.args[1], "MozAXGgC1Mc")
        statuses = {track["key"]: result["status"] for track, result in results}
        self.assertEqual(statuses["sugar"], "upgrade")
        self.assertEqual(statuses["song"], "no-explicit-version")
        self.assertEqual(statuses["explicit"], "explicit")
        # Recorded, so the next pass moves on instead of asking again.
        self.assertTrue(library._edition_checked("clean000001", "Artist", "Song"))
        self.assertTrue(library._edition_checked("MozAXGgC1Mc", "Maroon 5", "Sugar"))
        self.assertEqual([t["key"] for t in editions.cached()], ["sugar"])  # the mock swapped nothing

    def test_on_air_pinned_local_and_clean_requests_are_left_alone(self):
        playing = self.cache("sugar", "Maroon 5", "Sugar", "iPcX6EpJI3o")
        self.cache("linked", "Maroon 5", "Sugar", "iPcX6EpJI3o",
                   source_url="https://music.youtube.com/watch?v=MozAXGgC1Mc")
        self.cache("local", "Maroon 5", "Sugar", "iPcX6EpJI3o", source="local")
        self.cache("asked", "Maroon 5", "Sugar (Clean)", "iPcX6EpJI3o")
        self.assertEqual([t["key"] for t in editions.cached()], ["sugar"])
        with patch.object(library, "upgrade") as upgrade:
            self.assertEqual(editions.run_batch(10, protect=lambda: {str(playing)}), [])
        upgrade.assert_not_called()
        db.write("UPDATE tracks SET cache_used_at=? WHERE key='sugar'", (library.time.time(),))
        with patch.object(library, "upgrade") as upgrade:
            self.assertEqual(editions.run_batch(10, protect=lambda: set()), [])
        upgrade.assert_not_called()

    def test_failed_swap_keeps_audio_and_retries_later(self):
        self.cache("sugar", "Maroon 5", "Sugar", "iPcX6EpJI3o")
        with patch.object(library, "upgrade", return_value=False):
            self.assertFalse(editions.run_batch(10, protect=lambda: set())[0][1]["swapped"])
        self.assertTrue(library._edition_checked("iPcX6EpJI3o", "Maroon 5", "Sugar"))
        with patch.object(library.time, "time", return_value=library.time.time() + 3700):
            self.assertFalse(library._edition_checked("iPcX6EpJI3o", "Maroon 5", "Sugar"))

    def test_dry_run_reports_without_touching_anything(self):
        self.cache("sugar", "Maroon 5", "Sugar", "iPcX6EpJI3o")
        self.cache("mooo", "Doja Cat", "MOOO!", "0PKpzd4HcjU", duration=285)
        self.answers["0PKpzd4HcjU"] = song("0PKpzd4HcjU", "MOOO!", ["Doja Cat"], "MOOO!", 285, False)
        with patch.object(library, "upgrade") as upgrade:
            results = editions.run_batch(None, dry_run=True, unchecked_only=False)
        upgrade.assert_not_called()
        self.assertEqual({t["key"]: r["upgrade"] for t, r in results},
                         {"sugar": "MozAXGgC1Mc", "mooo": "5wIeHP6dscU"})
        self.assertFalse((self.root / "source-info" / "edition-checks").exists())

    def test_outage_stops_the_pass(self):
        self.cache("sugar", "Maroon 5", "Sugar", "iPcX6EpJI3o")
        self.answers["Maroon 5 Sugar"] = sourceio.SourceError("offline")
        results = editions.run_batch(10, protect=lambda: set())
        self.assertEqual(results[0][1]["status"], "unreachable")
        self.assertFalse(library._edition_checked("iPcX6EpJI3o", "Maroon 5", "Sugar"))

    def test_legacy_title_only_checks_are_looked_at_again(self):
        path = library._edition_check_path("iPcX6EpJI3o", "Maroon 5", "Sugar")
        path.parent.mkdir(parents=True)
        path.write_text('{"version": 1, "at": %f, "success": true}' % library.time.time())
        self.assertFalse(library._edition_checked("iPcX6EpJI3o", "Maroon 5", "Sugar"))


class TestSwap(CachedBase):
    def prepare(self):
        old = self.cache("sugar", "Maroon 5", "Sugar", "iPcX6EpJI3o", lufs=-14, intro_sec=1, outro_sec=200,
                         bpm=120)
        track = dict(db.one("SELECT * FROM tracks WHERE key='sugar'"))
        return old, track

    def fake_pipeline(self, duration=236.0):
        raw = self.root / "raw.webm"
        raw.write_bytes(b"downloaded")

        def render(source, target, gain, fmt=None):
            target.write_bytes(b"explicit audio")
            return True
        tonal = {name: None for name in library.TONAL_FIELDS}
        tonal["bpm"] = 120.0
        return (patch.object(library, "fetch_recording", return_value=("MozAXGgC1Mc", raw)),
                patch.object(library, "measure", return_value={"integrated": -10.0, "true_peak": -1.0,
                                                               "samples": [], "duration": duration}),
                patch.object(library, "_render", side_effect=render),
                patch.object(library.analysis, "profile", return_value=tonal),
                patch.object(library, "AUDIO_DIR", self.root))

    def test_swap_moves_file_and_source_together(self):
        old, track = self.prepare()
        patches = self.fake_pipeline()
        with patches[0], patches[1], patches[2], patches[3], patches[4]:
            self.assertTrue(library.upgrade(track, "MozAXGgC1Mc", lambda: set()))
        row = db.one("SELECT * FROM tracks WHERE key='sugar'")
        self.assertEqual(row["video_id"], "MozAXGgC1Mc")
        self.assertEqual(Path(row["file"]).read_bytes(), b"explicit audio")
        self.assertFalse(old.exists())
        self.assertTrue(library._edition_checked("MozAXGgC1Mc", "Maroon 5", "Sugar"))

    def test_old_file_kept_while_it_is_on_air(self):
        old, track = self.prepare()
        patches = self.fake_pipeline()
        with patches[0], patches[1], patches[2], patches[3], patches[4]:
            self.assertTrue(library.upgrade(track, "MozAXGgC1Mc", lambda: {str(old)}))
        self.assertTrue(old.exists())

    def test_a_different_length_is_not_the_same_record(self):
        old, track = self.prepare()
        patches = self.fake_pipeline(duration=320.0)
        with patches[0], patches[1], patches[2], patches[3], patches[4]:
            self.assertFalse(library.upgrade(track, "MozAXGgC1Mc", lambda: set()))
        row = db.one("SELECT * FROM tracks WHERE key='sugar'")
        self.assertEqual((row["video_id"], row["file"]), ("iPcX6EpJI3o", str(old)))
        self.assertTrue(old.exists())
        self.assertFalse(library._cache_path("MozAXGgC1Mc").exists())

    def test_download_failure_keeps_the_working_audio(self):
        old, track = self.prepare()
        with patch.object(library, "fetch_recording", side_effect=sourceio.SourceError("unavailable")), \
             patch.object(library, "AUDIO_DIR", self.root):
            self.assertFalse(library.upgrade(track, "MozAXGgC1Mc", lambda: set()))
        row = db.one("SELECT * FROM tracks WHERE key='sugar'")
        self.assertEqual((row["video_id"], row["file"]), ("iPcX6EpJI3o", str(old)))

    def test_a_track_being_prepared_is_left_alone(self):
        _, track = self.prepare()
        library._INFLIGHT["sugar"] = threading.Event()
        self.addCleanup(library._INFLIGHT.pop, "sugar", None)
        with patch.object(library, "_ensure_locked") as ensure:
            self.assertFalse(library.upgrade(track, "MozAXGgC1Mc"))
        ensure.assert_not_called()

    def test_preparing_a_clean_cached_song_swaps_it(self):
        from radio import importer
        old, track = self.prepare()
        patches = self.fake_pipeline()
        with patches[0] as fetch, patches[1], patches[2], patches[3], patches[4], \
             patch.object(importer, "refresh_tags", side_effect=lambda row, path: row):
            ready = library._ensure_locked(track)
        self.assertEqual(fetch.call_args.kwargs["video_id"], "MozAXGgC1Mc")
        self.assertEqual(ready["video_id"], "MozAXGgC1Mc")
        self.assertTrue(old.exists())  # eviction's job; it might still be on a deck

    def test_preparing_an_explicit_cached_song_keeps_it(self):
        from radio import importer
        self.cache("mooo", "Doja Cat", "MOOO!", "5wIeHP6dscU", duration=286, bpm=100)
        track = dict(db.one("SELECT * FROM tracks WHERE key='mooo'"))
        with patch.object(library, "fetch_recording") as fetch, patch.object(library, "resolve") as resolve, \
             patch.object(importer, "refresh_tags", side_effect=lambda row, path: row):
            self.assertEqual(library._ensure_locked(track)["file"], track["file"])
        fetch.assert_not_called()
        resolve.assert_not_called()
        self.assertTrue(library._edition_checked("5wIeHP6dscU", "Doja Cat", "MOOO!"))


if __name__ == "__main__":
    unittest.main()
