"""Getting audio onto disk, at a consistent level, with its shape measured.

Pipeline per track:
    resolve  -> pick the best source match. Refuses live takes, music videos,
                karaoke, covers and pitched re-uploads; prefers the
                auto-generated upload of the actual release
    fetch    -> download bestaudio
    render   -> loudness-normalise to the configured LUFS, encode to opus
    analyse  -> parse the ebur128 loudness envelope to find where the track
                actually starts and where it winds down

That last step is what lets the hosts talk up the post: we know when the
music arrives, so we know when to stop speaking.

See NOTICE.md. Audio here is transient, local, personal, and never served
outside this machine.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import threading
import time
import uuid
from pathlib import Path
from typing import Any

from . import analysis, config, db, sourceio, structure, versions, ytmusic

AUDIO_DIR = config.CACHE_DIR / "audio"
# Work in progress: downloads (.raw_*) and renders (.tmp_*). Never evicted as
# cache and never served; the janitor sweeps up what a crash leaves behind.
RAW_PREFIX = ".raw_"
STAGING_PREFIX = ".tmp_"
_RESOLVE_LOCK = threading.Lock()
_INFLIGHT: dict[str, threading.Event] = {}


def _log(*parts: Any) -> None:
    if config.DEBUG:
        print("[library]", *parts, flush=True)


# --------------------------------------------------------------------------
# Resolution
# --------------------------------------------------------------------------
# A performance, not the record. Parenthesised forms are the strong signals;
# a bare "live" is not, because plenty of songs are called Live Forever.
LIVE_MARKERS = (
    r"\(\s*live\b", r"\[\s*live\b", r"\blive\s*\)", r"[-–]\s*live\b",
    r"\blive (?:at|in|from|on|version|performance|video|session)\b",
    r"\bin concert\b", r"\bconcert\b", r"\bunplugged\b", r"\bacoustic session\b",
    r"\b(?:aol|abbey road|bbc|kexp|npr) sessions?\b", r"\btiny desk\b",
    r"\bboiler room\b", r"\b(?:dj|full) set\b", r"\bsetlist\b",
    r"\bfestival\b", r"\btour\b", r"\bencore\b", r"\bcrowd\b",
)

# A video, which routinely means an intro, an outro, or dialogue over the top.
# Weezer's Buddy Holly video runs 4:02 against a 2:40 record.
VIDEO_MARKERS = (
    r"\bofficial (?:music )?video\b", r"\bmusic video\b", r"\bofficial mv\b",
    r"\(\s*video\s*\)", r"\bvisuali[sz]er\b", r"\bshort film\b",
)

NON_MUSIC_MARKERS = (r"\bgameplay\b", r"\bbeamng(?:\.drive)?\b", r"\b(?:gaming|car) montage\b",
                     r"\b(?:reaction|tutorial|walkthrough)\b")

# Alternate editions require an explicit request when original preference is on.
VARIANT_WORDS = (
    "acoustic", "unplugged", "demo", "alternate version", "alternative version",
    "alt version", "alt. version", "reprise", "rework", "radio edit",
    "single version", "extended mix", "extended version", "mono mix",
    "re-recorded", "rerecorded", "taylor's version", "instrumental version",
    "orchestral version", "piano version", "stripped",
)

# Descriptions that give the game away even when the title is clean.
LIVE_IN_DESCRIPTION = (
    r"\blive (?:at|in|from|performance|recording)\b", r"\brecorded live\b",
    r"\bperformed live\b", r"\bin concert\b",
    r"\blive audio\b",
)
VIDEO_IN_DESCRIPTION = (
    r"\bofficial (?:music )?video\b", r"\bmusic video by\b",
)

# Auto-generated uploads of the actual release. The single most reliable
# marker of release audio; it does not establish whether lyrics are censored.
ART_TRACK = (r"provided to youtube by", r"auto-?generated by youtube")

# Re-encoded, pitched or "enhanced" uploads.
TAMPERED = (r"artificial intelligence", r"\bai (?:remaster|upscal)",
            r"\bspeed(?:ed)? up\b", r"\bpitched\b", r"\bbass boost")


def _matches(text: str, patterns: tuple[str, ...], wanted: str) -> str | None:
    """First pattern that hits the text but not the thing we asked for.

    The guard matters: searching for Oasis' Live Forever must not reject every
    result for containing the word live.
    """
    for pattern in patterns:
        if re.search(pattern, text) and not re.search(pattern, wanted):
            return pattern
    return None


def classify(entry: dict[str, Any], artist: str, title: str) -> dict[str, Any]:
    """What kind of upload is this? Used for both rejection and ranking."""
    name = (entry.get("title") or "").lower()
    channel = (entry.get("channel") or entry.get("uploader") or "").lower()
    description = (entry.get("description") or "").lower()[:600]
    # The guard string carries both shapes a result can take, because search
    # titles are written "Artist - Title". Without the dashed form, asking for
    # AC/DC's Live Wire matches the "- live" marker and every single candidate
    # is thrown away.
    wanted = f"{artist} - {title} | {artist} {title}".lower()
    haystack = f"{name} {description}"

    art_track = bool(_matches(haystack, ART_TRACK, "")
                     or channel.endswith(" - topic"))
    official_audio = bool(re.search(r"\bofficial audio\b", name))

    # The title outranks the description when they disagree. Label boilerplate
    # is frequently wrong: Sony's upload of Blue In Green is titled "(Official
    # Audio)" and described as "Official music video for...", and the title is
    # the one telling the truth.
    titled_video = bool(_matches(name, VIDEO_MARKERS, wanted))
    described_video = bool(_matches(description, VIDEO_IN_DESCRIPTION, wanted))
    clean, explicit = versions.metadata_edition(entry, artist, title)

    return {
        "live": not versions._tagged(title, r"live(?:\s+(?:at|in|from)[^\])]+)?") and bool(_matches(name, LIVE_MARKERS, wanted)
                     or _matches(description, LIVE_IN_DESCRIPTION, wanted)
                     or (entry.get("live_status") or "") in
                     ("is_live", "was_live", "post_live")),
        "video": titled_video or (described_video and not
                                  (official_audio or art_track)),
        "non_music": bool(_matches(name, NON_MUSIC_MARKERS, wanted)),
        "art_track": art_track,
        "clean": clean,
        "explicit": explicit,
        "tampered": bool(_matches(haystack, TAMPERED, wanted)),
        "lyrics": bool(re.search(r"\blyrics?\b", name)),
        # Plain words rather than patterns, so asking for "Creep - Acoustic"
        # guards correctly against a result titled "Creep (Acoustic)". A
        # bracketed pattern would miss the dashed request entirely.
        "variant": any(word in name and word not in wanted
                       for word in VARIANT_WORDS) or any(
                           word not in wanted and re.search(r"\b" + word + r"\s+(?:version|performance|session|recording|take)\b", description)
                           for word in ("acoustic", "stripped", "unplugged")),
        "official_audio": bool(re.search(r"\bofficial audio\b", name)),
        "name": name, "channel": channel,
    }


def _candidate_score(entry: dict[str, Any], artist: str, title: str,
                     expected_ms: int, allow_video: bool = False
                     ) -> float | None:
    """Rank one search result. None means disqualified."""
    name = (entry.get("title") or "").lower()
    channel = (entry.get("channel") or entry.get("uploader") or "").lower()
    duration = entry.get("duration") or 0

    wanted = f"{artist} - {title} | {artist} {title}".lower()
    rejects = [str(k).lower() for k in
               (config.station.get("selection.reject_keywords") or [])]
    for word in rejects:
        # Only reject if the junk word isn't part of what we actually asked for.
        if word in name and word not in wanted:
            return None

    kind = classify(entry, artist, title)
    wants_clean = versions.is_clean_label(title)
    avoid_clean = config.station.get("selection.avoid_clean_versions", True)
    if avoid_clean and kind["clean"] and not wants_clean:
        return None
    if wants_clean and kind["explicit"]:
        return None
    if kind["live"] or kind["tampered"] or kind["non_music"]:
        return None
    if kind["variant"] and config.station.get("selection.prefer_original_recording", True):
        return None
    if kind["video"] and not allow_video:
        return None

    if expected_ms and duration:
        tolerance = float(config.station.get("selection.duration_tolerance", 0.18) or 0.18)
        expected = expected_ms / 1000.0
        if abs(duration - expected) / expected > tolerance:
            return None
    if duration and (duration < 45 or duration > 900):
        return None

    score = 0.0
    if (avoid_clean and kind["explicit"]) or (wants_clean and kind["clean"]):
        score += 2.0
    # An auto-generated upload of the release itself beats everything. The
    # description marker is what actually catches these -- the "- Topic"
    # channel suffix is usually absent from search results.
    if kind["art_track"]:
        score += 6.0
    if kind["official_audio"]:
        score += 3.0
    if kind["video"]:
        score -= 4.0        # only reachable on the fallback pass
    if kind["lyrics"]:
        score -= 2.5        # often re-encoded, sometimes pitched
    if kind["variant"]:
        # A different take of the same song. Enough to lose to a plain
        # version, not enough to be unusable when it is all there is.
        score -= 7.0
    if db.norm(artist) and db.norm(artist) in db.norm(name + " " + channel):
        score += 2.0
    if db.norm(title) and db.norm(title) in db.norm(name):
        score += 2.0
    if entry.get("channel_is_verified"):
        score += 1.0
    if expected_ms and duration:
        drift = abs(duration - expected_ms / 1000.0)
        score += max(0.0, 2.0 - drift / 5.0)
    return score


def _same_recording(entry: dict[str, Any], artist: str, title: str) -> bool:
    name = entry.get('title') or ''
    name = re.sub(r'\s*[\[(](?:official(?: music)?(?: video| audio)?|audio|lyrics?|explicit|uncensored)[^\])]*[\])]',
                  '', name, flags=re.I).strip()
    parts = re.split(r'\s[-–—]\s', name, maxsplit=1)
    credit, song = parts if len(parts) == 2 else ('', name)
    primary = db.norm(db.primary_artist(artist))
    channel = db.norm(entry.get('channel') or entry.get('uploader') or '')
    channel = re.sub(r'\s*(?:official|vevo|topic)$', '', channel).strip()
    named_artist = not primary or primary == 'unknown' or (
        primary in db.norm(credit) if credit else channel in (primary, db.norm(artist)))
    return db.norm(song) == db.norm(title) and named_artist


def _source_info(video_id: str) -> dict[str, Any]:
    """Cache source labels separately from catalogue titles and user edits."""
    if not re.fullmatch(r"[A-Za-z0-9_-]{11}", video_id or ""):
        return {}
    path = config.CACHE_DIR / "source-info" / f"{video_id}.json"
    try:
        info = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(info, dict) and info.get("id") == video_id:
            return info
    except (OSError, ValueError):
        pass
    try:
        info = sourceio.describe(video_id)
        if isinstance(info, dict) and info.get("title"):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(info), encoding="utf-8")
            return info
    except (sourceio.SourceError, OSError):
        pass
    return {}


def _edition_check_path(video_id: str, artist: str, title: str) -> Path:
    identity = json.dumps([video_id, db.norm(artist), db.norm(title)], ensure_ascii=False)
    name = hashlib.sha256(identity.encode("utf-8")).hexdigest()
    return config.CACHE_DIR / "source-info" / "edition-checks" / (name + ".json")


def _edition_checked(video_id: str, artist: str, title: str) -> bool:
    try:
        data = json.loads(_edition_check_path(video_id, artist, title).read_text(encoding="utf-8"))
        # Version 1 compared titles only, and a clean auto-generated upload is
        # titled exactly like the explicit one. Those get looked at again.
        if data.get("version") != 2:
            return False
        if not data.get("success", True):
            ttl = 3600
        elif data.get("ytmusic"):
            ttl = 30 * 86400
        else:
            ttl = 6 * 3600  # titles only; ask YouTube Music again later
        return time.time() - float(data["at"]) < ttl
    except (OSError, ValueError, TypeError, KeyError):
        return False


def _edition_flagged(video_id: str, artist: str, title: str) -> bool:
    try:
        data = json.loads(_edition_check_path(video_id, artist, title).read_text(encoding="utf-8"))
        return data.get("version") == 2 and bool(data.get("ytmusic"))
    except (OSError, ValueError, TypeError, KeyError):
        return False


def _record_edition_check(video_id: str, artist: str, title: str, *, success=True,
                          flagged=False, status: str | None = None) -> None:
    # Evidence of an edition search, not a claim that audio is proven explicit.
    # `flagged` says YouTube Music's explicit flag was part of the answer.
    try:
        path = _edition_check_path(video_id, artist, title)
        path.parent.mkdir(parents=True, exist_ok=True)
        record = {"version": 2, "at": time.time(), "success": success, "ytmusic": bool(flagged)}
        if status:
            record["status"] = status
        path.write_text(json.dumps(record), encoding="utf-8")
    except OSError:
        pass


def resolve(artist: str, title: str, expected_ms: int = 0, *, exclude=()) -> str | None:
    """Return the best matching source video id, or None."""
    count = int(config.station.get("downloader.search_results", 5) or 5)
    query = f"ytsearch{count}:{artist} - {title}"
    options = {
        "quiet": True, "no_warnings": True, "skip_download": True,
        "extract_flat": "in_playlist", "socket_timeout": 15, "retries": 1,
        "default_search": "ytsearch",
    }
    info = sourceio.search(query, options)

    candidates = [e for e in ((info or {}).get("entries") or [])
                  if e and re.fullmatch(r"[\w-]{11}", e.get("id") or "")]

    prefer_explicit = (config.station.get("selection.avoid_clean_versions", True)
                       and not versions.is_clean_label(title))
    # An unlabelled Topic upload can be the clean edition, titled exactly like
    # the explicit one. YouTube Music's explicit flag tells them apart: when it
    # has an explicit release of this song, that goes to the front. When it
    # only has clean ones, the song has no explicit version and nothing else
    # changes. Exact source URLs bypass resolution entirely.
    hint = ytmusic.explicit_choice(artist, title, expected_ms) if prefer_explicit else None
    flagged = [song["video_id"] for song in (hint or {}).get("explicit", [])]
    if flagged:
        known = {entry["id"] for entry in candidates}
        for song in hint["explicit"]:
            if song["video_id"] not in known:
                # Scored on its own details below, like any search result.
                candidates.append({"id": song["video_id"], "title": song["title"],
                                   "duration": song["duration"] or None})
                known.add(song["video_id"])
    # Without that answer, compare a targeted search before accepting an
    # unlabelled upload, instead of searching only after every result has
    # already been rejected.
    searched_explicit = False
    if prefer_explicit and not (hint and hint["matched"]):
        try:
            extra = sourceio.search(query + " explicit audio", options)
            searched_explicit = True
            known = {entry["id"] for entry in candidates}
            for entry in ((extra or {}).get("entries") or []):
                if (entry and re.fullmatch(r"[\w-]{11}", entry.get("id") or "")
                        and entry["id"] not in known and _same_recording(entry, artist, title)):
                    candidates.append(entry)
                    known.add(entry["id"])
        except Exception as error:
            _log("explicit-edition search failed", artist, title, error)
    for allow_video in (False, True):
        if allow_video and config.station.get("selection.avoid_music_videos", True):
            continue
        ranked = []
        require_identity = any(entry['id'] in exclude for entry in candidates)
        for entry in candidates:
            if entry['id'] in exclude:
                continue
            if (prefer_explicit and classify(entry, artist, title)["explicit"]
                    and not _same_recording(entry, artist, title)):
                continue
            if require_identity:
                # A fallback must still identify this recording; a merely
                # high-ranked search result is not enough after the first fails.
                # YouTube Music already matched its releases by song and artist.
                if ((entry['id'] not in flagged and not _same_recording(entry, artist, title)) or
                        classify(entry, artist, title)['variant']):
                    continue
            score = _candidate_score(entry, artist, title, expected_ms,
                                     allow_video=allow_video)
            if score is None:
                continue
            ranked.append((score, entry))

        for score, entry in sorted(ranked, key=lambda candidate: (
                candidate[1]["id"] in flagged,
                prefer_explicit and classify(candidate[1], artist, title)["explicit"], candidate[0]),
                reverse=True):
            details = _source_info(entry["id"])
            entry = {**entry, **{k: v for k, v in details.items() if v is not None}}
            score = _candidate_score(entry, artist, title, expected_ms, allow_video=allow_video)
            if score is None:
                continue
            kind = classify(entry, artist, title)
            tags = [k for k in ("art_track", "official_audio", "video", "lyrics", "explicit", "clean")
                    if kind[k]] + (["flagged explicit"] if entry["id"] in flagged else [])
            _log("resolved", artist, "-", title, "->", entry["id"],
                 f"(score {score:.1f}"
                 + (f", {'+'.join(tags)}" if tags else "") + ")")
            if allow_video:
                _log("  only a video was available for", title)
            if flagged and entry["id"] not in flagged:
                _log("  no explicit release was usable for", title)
            if prefer_explicit and (searched_explicit or hint is not None):
                _record_edition_check(
                    entry["id"], artist, title, flagged=hint is not None,
                    status="explicit" if entry["id"] in flagged else
                    "no-explicit-version" if hint and hint["matched"] and not flagged else None)
            return entry["id"]

    _log("no acceptable match for", artist, "-", title,
         f"({len(candidates)} candidates rejected by source/version checks)")
    return None


# --------------------------------------------------------------------------
# Fetch + render
# --------------------------------------------------------------------------
def _ffmpeg(args: list[str], timeout: int = 300) -> subprocess.CompletedProcess:
    return subprocess.run(
        [config.FFMPEG, "-hide_banner", "-nostdin", "-y", *args],
        capture_output=True, text=True, timeout=timeout,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )


def _download_raw(video_id: str, destination: Path) -> Path | None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    # Console pulls and radio can fetch the same song in separate processes.
    # Each owns its staging files, including any .part file left on failure.
    destination = destination.with_name(destination.name + "_" + uuid.uuid4().hex)
    options = {
        "quiet": True, "no_warnings": True,
        "format": "bestaudio/best",
        "outtmpl": str(destination.with_suffix(".%(ext)s")),
        "socket_timeout": 20, "retries": 2,
        "noplaylist": True,
        "overwrites": True,
    }
    try:
        sourceio.download(video_id, options)
    except Exception:
        for part in destination.parent.glob(destination.name + ".*"):
            part.unlink(missing_ok=True)
        raise
    matches = sorted(destination.parent.glob(destination.stem + ".*"))
    return matches[0] if matches else None


def _unavailable(error: Exception) -> bool:
    """Only source-specific failures warrant trying a different upload."""
    message = str(error).lower()
    return any(phrase in message for phrase in (
        'please sign in', 'sign in to confirm', 'video unavailable',
        'video is unavailable', 'private video', 'video has been removed',
        'not available in your country', 'copyright', 'http error 403',
        'requested format is not available'))


def fetch_recording(artist: str, title: str, expected_ms: int = 0, *,
                    video_id: str | None = None, pinned: bool = False,
                    use_cache: bool = False, on_attempt=None) -> tuple[str, Path | None]:
    """Try up to three matching uploads; explicit video links stay pinned.

    Returns the chosen ID and raw audio, or the finished cache file on a hit.
    Timeouts and disk/encoding failures do not trigger another download.
    """
    if pinned and not video_id:
        raise sourceio.SourceError('The requested video link has no usable video ID.')
    excluded = {row['video_id'] for row in db.query(
        'SELECT video_id FROM unavailable_sources WHERE retry_after>?', (time.time(),))}
    attempted = set()
    last_error = None
    for attempt in range(1 if pinned else 3):
        if not video_id or (not pinned and video_id in excluded):
            video_id = resolve(artist, title, expected_ms, exclude=excluded | attempted)
        if not video_id or video_id in attempted:
            break
        attempted.add(video_id)
        if on_attempt:
            on_attempt(video_id, attempt)
        cached = _cache_path(video_id)
        if use_cache and cached.is_file():
            return video_id, cached
        try:
            raw = _download_raw(video_id, AUDIO_DIR / f'.raw_{video_id}')
            if raw:
                db.write('DELETE FROM unavailable_sources WHERE video_id=?', (video_id,))
            return video_id, raw
        except sourceio.SourceError as error:
            if pinned or not _unavailable(error):
                raise
            last_error = error
            excluded.add(video_id)
            db.write('INSERT OR REPLACE INTO unavailable_sources(video_id,retry_after,reason) VALUES(?,?,?)',
                     (video_id, time.time() + 86400, str(error)[:400]))
            _log('source unavailable; trying another matching upload', video_id)
            video_id = None
    if last_error:
        raise sourceio.SourceError('Matching uploads were unavailable. Try another video link or retry later. '
                                   + str(last_error)[:220]) from last_error
    return '', None


def _render(source: Path, target: Path, gain_db: float,
            fmt: str | None = None) -> bool:
    """Apply a single linear gain and encode to the working format.

    Deliberately NOT ffmpeg's one-pass `loudnorm`, which is a dynamic
    processor: it flattens a mastered record to about 1 LU of range, which
    kills the contrast that makes ducking and crossfades audible. Measuring
    first and applying one gain keeps the record's own dynamics intact.
    """
    rate = int(config.station.get("audio.sample_rate", 48000) or 48000)
    fmt = fmt or str(config.station.get("cache.format", "opus") or "opus")

    if fmt == "opus":
        codec = ["-c:a", "libopus", "-b:a",
                 str(config.station.get("cache.opus_bitrate", "160k") or "160k")]
    elif fmt == "flac":
        codec = ["-c:a", "flac", "-compression_level", "5"]
    elif fmt in ("m4a", "aac"):
        codec = ["-c:a", "aac", "-b:a",
                 str(config.station.get("cache.aac_bitrate", "192k") or "192k")]
    else:
        codec = ["-c:a", "pcm_s16le"]

    # A gentle limiter only catches the rare inter-sample overshoot; with the
    # gain already ceiling-limited it should almost never engage.
    chain = f"volume={gain_db:.2f}dB,alimiter=limit=0.97:level=disabled"

    # Render beside the target and publish with one rename. A render that is
    # killed, times out or fails leaves no half-written file under the final
    # name for a cache check (or a deck) to mistake for the finished record.
    # The extension stays last so ffmpeg still picks the container from it.
    staging = target.with_name(f"{STAGING_PREFIX}{uuid.uuid4().hex[:12]}_{target.name}")
    try:
        try:
            result = _ffmpeg([
                "-i", str(source), "-vn", "-map_metadata", "-1",
                "-af", chain, "-ar", str(rate), "-ac", "2",
                *codec, str(staging),
            ])
        except subprocess.TimeoutExpired:
            _log("render timed out", target.name)
            return False
        if result.returncode != 0:
            _log("render failed", result.stderr[-500:])
            return False
        if not staging.is_file() or staging.stat().st_size <= 1024:
            return False
        try:
            os.replace(staging, target)
        except OSError as error:  # a reader holding the old file open (Windows)
            _log("could not publish render", target.name, error)
            return False
        return True
    finally:
        staging.unlink(missing_ok=True)


_FRAME = re.compile(r"t:\s*([\d.]+).*?\sS:\s*(-?[\d.]+|-inf)")
_INTEGRATED = re.compile(r"^\s*I:\s*(-?[\d.]+|-inf)\s*LUFS", re.MULTILINE)
_TRUE_PEAK = re.compile(r"Peak:\s*(-?[\d.]+|-inf)\s*dBFS")


def measure(path: Path) -> dict[str, Any]:
    """One ebur128 pass: integrated loudness, true peak, loudness envelope.

    The envelope is what tells us where a record actually starts. Where
    short-term loudness first climbs to within a few LU of the track's median
    and stays there is, in practice, the end of the intro -- the window a DJ
    talks over.
    """
    result = _ffmpeg(["-i", str(path), "-af", "ebur128=framelog=info:peak=true",
                      "-f", "null", "-"], timeout=240)
    stderr = result.stderr or ""

    samples: list[tuple[float, float]] = []
    for line in stderr.splitlines():
        match = _FRAME.search(line)
        if not match:
            continue
        try:
            moment = float(match.group(1))
            short_term = float(match.group(2))
        except ValueError:
            continue  # -inf during leading silence
        if short_term > -70:
            samples.append((moment, short_term))

    def _last(pattern: re.Pattern[str], default: float) -> float:
        found = pattern.findall(stderr)
        try:
            return float(found[-1]) if found else default
        except ValueError:
            return default

    return {
        "integrated": _last(_INTEGRATED, -23.0),
        "true_peak": _last(_TRUE_PEAK, -1.0),
        "samples": samples,
        "duration": _decoded_seconds(stderr),
    }


_PROGRESS = re.compile(r"time=(\d+):(\d\d):(\d\d(?:\.\d+)?)")
_HEADER_DURATION = re.compile(r"Duration:\s*(\d+):(\d\d):(\d\d(?:\.\d+)?)")


def _decoded_seconds(stderr: str) -> float:
    """How much audio the pass just decoded, from ffmpeg's own report.

    The final progress line counts what was actually decoded, which is the
    number we want; the container header is the fallback. 0.0 when neither
    is there, and the caller probes instead.
    """
    for pattern in (_PROGRESS, _HEADER_DURATION):
        found = pattern.findall(stderr or "")
        if found:
            hours, minutes, seconds = found[-1]
            value = int(hours) * 3600 + int(minutes) * 60 + float(seconds)
            if value > 0:
                return value
    return 0.0


def shape(samples: list[tuple[float, float]], duration: float) -> dict[str, float]:
    """Turn a loudness envelope into intro and outro points."""
    fallback = float(config.station.get("talk_placement.assumed_intro", 12.0) or 12.0)
    if len(samples) < 8:
        return {"intro_sec": fallback, "outro_sec": max(0.0, duration - 8.0)}

    values = sorted(value for _, value in samples)
    median = values[len(values) // 2]

    intro = _sustained_crossing(samples, median - 3.0, hold=1.5)
    intro = min(max(intro if intro is not None else fallback, 0.0), 45.0)

    outro = _last_crossing(samples, median - 6.0)
    if outro is None:
        outro = max(0.0, duration - 8.0)

    return {"intro_sec": intro, "outro_sec": outro}


def gain_for(integrated: float, true_peak: float) -> float:
    """Gain in dB to hit the target loudness without clipping."""
    target = float(config.station.get("audio.target_lufs", -14.0) or -14.0)
    ceiling = float(config.station.get("audio.true_peak_ceiling", -1.5) or -1.5)
    wanted = target - integrated
    headroom = ceiling - true_peak
    # Never push a track into the ceiling just to hit the loudness target.
    return max(-24.0, min(wanted, headroom, 24.0))


def trim_db(track: Any) -> float:
    """Gain a player should add so this track airs at the target loudness.

    Cached downloads were rendered at the target already: 0. Local files play
    as they are on disk, so they get the same ceiling-limited gain a render
    would have baked in. Without a measured peak, only ever turn one down.
    """
    if db.field(track, "source") != "local":
        return 0.0
    lufs = db.field(track, "lufs")
    if lufs is None:
        return 0.0
    try:
        lufs = float(lufs)
        peak = db.field(track, "true_peak")
        if peak is None:
            target = float(config.station.get("audio.target_lufs", -14.0) or -14.0)
            return round(max(-24.0, min(0.0, target - lufs)), 2)
        return round(gain_for(lufs, float(peak)), 2)
    except (TypeError, ValueError):
        return 0.0


def _sustained_crossing(samples: list[tuple[float, float]], threshold: float,
                        hold: float) -> float | None:
    """First moment loudness goes above `threshold` and stays for `hold` sec."""
    start: float | None = None
    for moment, value in samples:
        if value >= threshold:
            if start is None:
                start = moment
            elif moment - start >= hold:
                return start
        else:
            start = None
    return None


def _last_crossing(samples: list[tuple[float, float]], threshold: float) -> float | None:
    for moment, value in reversed(samples):
        if value >= threshold:
            return moment
    return None


def _probe_duration(path: Path) -> float:
    try:
        result = subprocess.run(
            [config.FFPROBE, "-v", "error", "-show_entries", "format=duration",
             "-of", "json", str(path)],
            capture_output=True, text=True, timeout=30,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
        return float(json.loads(result.stdout)["format"]["duration"])
    except Exception:  # noqa: BLE001
        return 0.0


# --------------------------------------------------------------------------
# Public entry point
# --------------------------------------------------------------------------
def _cache_path(video_id: str) -> Path:
    fmt = str(config.station.get("cache.format", "opus") or "opus")
    digest = hashlib.sha1(video_id.encode()).hexdigest()[:16]
    return AUDIO_DIR / f"{digest}.{fmt}"


TONAL_FIELDS = ("bpm", "bpm_confidence", "key_tonic", "key_mode", "key_confidence",
                "camelot", "beat_offset", "beat_period", "beat_residual_ms", "downbeat_offset")


def _mark_used(key: str) -> None:
    """Note that this file was just prepared. Eviction orders by it.

    Recorded in the database rather than by touching the file: the file's
    mtime is part of the waveform, structure and stem cache identities, and
    bumping it would throw all three away.
    """
    db.write("UPDATE tracks SET cache_used_at=? WHERE key=?", (time.time(), key))


def ensure(track: dict[str, Any]) -> dict[str, Any] | None:
    """Make sure this track is on disk, analysed, and ready to schedule.

    Blocking and slow on a cache miss -- always call this from the prefetch
    worker, never from the playout path.
    """
    key = track["key"]

    # Collapse duplicate requests for the same track into one download.
    with _RESOLVE_LOCK:
        event = _INFLIGHT.get(key)
        if event is None:
            event = threading.Event()
            _INFLIGHT[key] = event
            owner = True
        else:
            owner = False
    if not owner:
        event.wait(timeout=180)
        row = db.one("SELECT * FROM tracks WHERE key=?", (key,))
        if not row or not row["file"]:
            return None
        ready = dict(row)
        ready["structure"] = structure.profile_for(ready)
        _mark_used(key)
        return ready

    try:
        ready = _ensure_locked(track)
        if ready and ready.get("file"):
            _mark_used(key)
            # This prefetch worker is the only place that decodes for cue
            # analysis; timeline construction reads the prepared cache only.
            ready["structure"] = structure.profile(ready["file"])
        return ready
    finally:
        with _RESOLVE_LOCK:
            _INFLIGHT.pop(key, None)
        event.set()


def upgrade(track: dict[str, Any], video_id: str, protect=None) -> bool:
    """Swap a cached track to another upload of the same record, in the background.

    The old audio keeps playing until the new file is rendered and checked;
    then one row update points the track at it. A track the feeder is
    preparing right now is left alone. `protect` returns the files still
    wanted on air; the old file is deleted only when it is not one of them
    (without it, eviction gets to it in its own time).
    """
    key = track["key"]
    with _RESOLVE_LOCK:
        if key in _INFLIGHT:
            return False
        event = threading.Event()
        _INFLIGHT[key] = event
    try:
        before = db.one("SELECT * FROM tracks WHERE key=?", (key,))
        if not before or not before["file"] or before["video_id"] == video_id:
            return False
        ready = _ensure_locked(dict(track), replacement=video_id)
        swapped = bool(ready and ready.get("file") and ready.get("video_id") != before["video_id"])
        old = Path(before["file"])
        if swapped and protect is not None and _same_file_key(ready["file"]) != _same_file_key(old):
            try:
                keep = {_same_file_key(p) for p in (protect() or ()) if p}
                if (_same_file_key(old) not in keep
                        and not db.one("SELECT key FROM tracks WHERE file=?", (str(old),))):
                    old.unlink(missing_ok=True)
            except OSError:
                pass  # a reader still has it open; eviction will get it
        if swapped:
            _log("swapped", track.get("artist"), "-", track.get("title"), before["video_id"], "->", ready["video_id"])
        return swapped
    finally:
        with _RESOLVE_LOCK:
            _INFLIGHT.pop(key, None)
        event.set()


def _ensure_locked(track: dict[str, Any], replacement: str | None = None) -> dict[str, Any] | None:
    """`replacement` swaps cached audio for that upload, keeping the old file on failure."""
    key = track["key"]
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)

    existing = db.one("SELECT * FROM tracks WHERE key=?", (key,))
    if existing and db.field(existing, "source_url"):
        from . import youtube
        track = youtube.hydrate(dict(existing))
        existing = track
    use_existing = True
    replacement_id = None
    fallback_existing = False
    verified_upgrade = False
    if replacement:
        # Local files and exact links are never swapped for another upload.
        if not (existing and existing["file"] and Path(existing["file"]).is_file()
                and db.field(existing, "source") != "local" and not db.field(existing, "source_url")):
            return dict(existing) if existing else None
        replacement_id, fallback_existing, use_existing, verified_upgrade = replacement, True, False, True
    elif (existing and existing["file"] and existing["video_id"]
            and db.field(existing, "source") != "local" and not db.field(existing, "source_url")
            and (config.station.get("selection.avoid_clean_versions", True)
                 or config.station.get("selection.prefer_original_recording", True)
                 or config.station.get("selection.avoid_music_videos", True))):
        info = _source_info(existing["video_id"])
        if (config.station.get("selection.avoid_clean_versions", True)
                and not versions.is_clean_label(track["title"])
                and not any(versions.metadata_edition(info, track["artist"], track["title"]))
                and _candidate_score(info, track["artist"], track["title"], track.get("expected_ms") or 0,
                    allow_video=not config.station.get("selection.avoid_music_videos", True)) is not None
                and not _edition_checked(existing["video_id"], track["artist"], track["title"])):
            fallback_existing = Path(existing["file"]).is_file()
            _log("checking explicit edition for cached recording", track["artist"], track["title"])
            # YouTube Music's flag first: it answers "is this upload the clean
            # one" directly, and only a proven clean upload with an explicit
            # sibling is replaced. Without an answer, search as before.
            found = ytmusic.verdict(existing["video_id"], track["artist"], track["title"],
                                    db.field(existing, "duration") or 0)
            if found is not None and found["status"] != "unknown":
                replacement_id = found["upgrade"]
                verified_upgrade = bool(replacement_id)
                _record_edition_check(existing["video_id"], track["artist"], track["title"],
                                      flagged=True, status=found["status"])
            else:
                try:
                    replacement_id = resolve(track["artist"], track["title"], track.get("expected_ms") or 0)
                except (sourceio.SourceError, OSError):
                    # This is an ambiguous working source, not a proven clean one.
                    # A network outage must not discard it or retry every pick.
                    replacement_id = None
                _record_edition_check(existing["video_id"], track["artist"], track["title"],
                                      success=bool(replacement_id and _edition_checked(
                                          replacement_id, track["artist"], track["title"])),
                                      flagged=bool(replacement_id and _edition_flagged(
                                          replacement_id, track["artist"], track["title"])))
            use_existing = not replacement_id or replacement_id == existing["video_id"]
        if info and _candidate_score(info, track["artist"], track["title"],
                                     track.get("expected_ms") or 0,
                                     allow_video=not config.station.get("selection.avoid_music_videos", True)) is None:
            use_existing = False
            _log("replacing alternate cached recording for", track["artist"], track["title"])
    if existing and existing["file"] and use_existing:
        path = Path(existing["file"])
        if path.exists():
            # Upgrade genre/embedded lyric evidence on the one track being
            # prepared, without rescanning the user's library or redoing DSP.
            from . import importer
            existing = importer.refresh_tags(dict(existing), path)
            # A file cached before tempo and key analysis existed would
            # otherwise never get it, because this early return skips the
            # whole pipeline. Fill the gap in place.
            if not db.field(existing, "bpm"):
                tonal = analysis.profile(path)
                db.write(
                    "UPDATE tracks SET bpm=?, bpm_confidence=?, key_tonic=?, "
                    "key_mode=?, key_confidence=?, camelot=?, beat_offset=?, "
                    "beat_period=?, beat_residual_ms=?, downbeat_offset=? WHERE key=?",
                    (tonal["bpm"], tonal["bpm_confidence"], tonal["key_tonic"],
                     tonal["key_mode"], tonal["key_confidence"],
                     tonal["camelot"], tonal["beat_offset"],
                     tonal["beat_period"], tonal["beat_residual_ms"],
                     tonal["downbeat_offset"], key))
                _log("backfilled analysis for", track.get("title"),
                     f"{tonal['bpm']:.0f}bpm {tonal['camelot'] or '?'}")
                existing = db.one("SELECT * FROM tracks WHERE key=?", (key,))
            return dict(existing)

    if existing and db.field(existing, "source") == "local":
        return None

    # A saved ID without usable audio may predate the edition preference.
    # Re-resolve it under the current rules instead of downloading it blindly.
    saved_id = existing["video_id"] if existing else None
    if (not db.field(existing, "source_url")
            and (config.station.get("selection.avoid_clean_versions", True)
                 or config.station.get("selection.prefer_original_recording", True)
                 or config.station.get("selection.avoid_music_videos", True))):
        saved_id = None
    try:
        video_id, raw = fetch_recording(
            track['artist'], track['title'], track.get('expected_ms') or 0,
            video_id=replacement_id or saved_id, pinned=bool(db.field(existing, 'source_url')), use_cache=True)
    except sourceio.SourceError:
        if not fallback_existing:
            raise
        _record_edition_check(existing["video_id"], track["artist"], track["title"], success=False)
        return dict(existing)
    if fallback_existing and (not video_id or not raw):
        _record_edition_check(existing["video_id"], track["artist"], track["title"], success=False)
        return dict(existing)
    if not video_id:
        db.write("UPDATE tracks SET blocked=1 WHERE key=?", (key,))
        return None
    if not fallback_existing:
        # A replacement moves video_id and file together, in the last write,
        # so the row never names one upload while playing another.
        db.write("UPDATE tracks SET video_id=? WHERE key=?", (video_id, key))

    def keep_existing() -> dict[str, Any]:
        _record_edition_check(existing["video_id"], track["artist"], track["title"], success=False)
        return dict(existing)

    final = _cache_path(video_id)
    measured: dict[str, Any] | None = None
    gain: float | None = None
    try:
        if not final.exists():
            if not raw:
                return keep_existing() if fallback_existing else None

            # Measure the source, then apply one gain. Analysing the raw file
            # also gets us the shape for free -- a linear gain does not move it.
            measured = measure(raw)
            gain = gain_for(measured["integrated"], measured["true_peak"])
            if not _render(raw, final, gain):
                return keep_existing() if fallback_existing else None
            _log(f"normalised {measured['integrated']:.1f} LUFS "
                 f"-> {measured['integrated'] + gain:.1f} ({gain:+.1f} dB)")
    finally:
        # The download is only ever a means to the render. Gone on success,
        # failure and timeout alike, so a crash-free run leaves no staging.
        if raw and raw != final:
            try:
                raw.unlink(missing_ok=True)
            except OSError:
                pass

    # The same recording this row already describes: what was measured and
    # analysed last time still holds, and decoding it again buys nothing.
    known = dict(existing) if existing and existing["video_id"] == video_id else {}
    reuse_shape = measured is None and all(
        known.get(name) is not None for name in ("duration", "intro_sec", "outro_sec", "lufs"))
    reuse_tonal = bool(known.get("bpm"))

    if reuse_shape:
        duration = float(known["duration"])
        stats = {"intro_sec": known["intro_sec"], "outro_sec": known["outro_sec"]}
        levels = {name: known.get(name) for name in
                  ("lufs", "source_lufs", "applied_gain_db", "true_peak")}
    else:
        if measured is None:  # cache hit on the audio, but no stored shape
            measured = measure(final)
        duration = float(measured.get("duration") or 0) or _probe_duration(final)
        stats = shape(measured["samples"], duration)
        if gain is not None:
            # Fresh render: lufs is what now plays, the rest is provenance.
            levels = {"lufs": measured["integrated"] + gain,
                      "source_lufs": measured["integrated"],
                      "applied_gain_db": gain,
                      "true_peak": measured["true_peak"] + gain}
        else:
            # Measured off the cached render itself, so it already is the
            # playing level; where it came from is only known if we kept it.
            levels = {"lufs": measured["integrated"],
                      "source_lufs": known.get("source_lufs"),
                      "applied_gain_db": known.get("applied_gain_db"),
                      "true_peak": measured["true_peak"]}

    old_length = float(db.field(existing, "duration") or 0) if existing else 0.0
    if (fallback_existing and video_id != existing["video_id"] and old_length
            and abs(duration - old_length) > max(8.0, old_length * 0.05)):
        # Another edition of one record runs within seconds of it. Anything
        # further off is some other recording: keep the one that works.
        _log("replacement runs", f"{duration:.0f}s against {old_length:.0f}s; keeping cached",
             track["artist"], "-", track["title"])
        if not db.one("SELECT key FROM tracks WHERE file=?", (str(final),)):
            try:
                final.unlink(missing_ok=True)
            except OSError:
                pass
        return keep_existing()

    # Tempo and key, so the director can pick a transition that suits the two
    # records rather than always reaching for the same crossfade.
    if reuse_tonal:
        tonal = {name: known.get(name) for name in TONAL_FIELDS}
    else:
        tonal = analysis.profile(final)

    db.write(
        "UPDATE tracks SET blocked=0, video_id=?, file=?, duration=?, intro_sec=?, outro_sec=?, "
        "lufs=?, source_lufs=?, applied_gain_db=?, true_peak=?, "
        "bpm=?, bpm_confidence=?, key_tonic=?, key_mode=?, "
        "key_confidence=?, camelot=?, beat_offset=?, beat_period=?, "
        "beat_residual_ms=?, downbeat_offset=?, cache_used_at=? WHERE key=?",
        (video_id, str(final), duration, stats["intro_sec"], stats["outro_sec"],
         levels["lufs"], levels["source_lufs"], levels["applied_gain_db"], levels["true_peak"],
         tonal["bpm"], tonal["bpm_confidence"],
         tonal["key_tonic"], tonal["key_mode"], tonal["key_confidence"],
         tonal["camelot"], tonal["beat_offset"], tonal["beat_period"],
         tonal["beat_residual_ms"], tonal["downbeat_offset"], time.time(), key),
    )
    if verified_upgrade and video_id == replacement_id:
        # YouTube Music named this upload as the explicit release.
        _record_edition_check(video_id, track["artist"], track["title"], flagged=True, status="explicit")
    _log("ready", track["artist"], "-", track["title"],
         f"{duration:.0f}s intro={stats['intro_sec']:.1f}s "
         f"outro={stats['outro_sec']:.1f}s "
         f"{tonal['bpm']:.0f}bpm {tonal['camelot'] or '?'}")
    row = db.one("SELECT * FROM tracks WHERE key=?", (key,))
    return dict(row) if row else None


# --------------------------------------------------------------------------
# Cache housekeeping
# --------------------------------------------------------------------------
def _same_file_key(path: Path | str) -> str:
    return os.path.normcase(str(Path(path).resolve()))


def evict(protect: set[str] | None = None) -> int:
    """Enforce the cache budget. Returns bytes freed.

    `protect` is every file the station still means to play: scheduled,
    queued, or being built right now. Those are never deleted, whatever the
    mode. Everything else goes least recently used first, where "used" is the
    later of its last airing and its last preparation (file mtime when the
    database knows neither).
    """
    protect = {_same_file_key(p) for p in (protect or set()) if p}
    protect.update(_same_file_key(row['file']) for row in db.query(
        "SELECT file FROM tracks WHERE source='local' AND file IS NOT NULL"))
    mode = str(config.station.get("cache.mode", "lru") or "lru")
    max_age = float(config.station.get("cache.max_age_hours", 168) or 0) * 3600
    budget = float(config.station.get("cache.max_size_gb", 6.0) or 0) * 1024**3
    # A file prepared moments ago may not have reached the queue yet; the
    # feeder holds it between ensure() and enqueue. Leave it alone a while.
    grace = float(config.station.get("cache.fresh_grace_minutes", 15) or 0) * 60

    used: dict[str, float] = {}
    for row in db.query("SELECT file, last_played, cache_used_at FROM tracks "
                        "WHERE file IS NOT NULL"):
        stamp = max(row["last_played"] or 0, row["cache_used_at"] or 0)
        if stamp:
            key = _same_file_key(row["file"])
            used[key] = max(used.get(key, 0), float(stamp))

    entries = []
    for path in AUDIO_DIR.glob("*"):
        if path.name.startswith((RAW_PREFIX, STAGING_PREFIX)):
            continue
        try:
            stat = path.stat()
        except OSError:
            continue
        if not path.is_file():
            continue
        entries.append((max(used.get(_same_file_key(path), 0), stat.st_mtime),
                        stat.st_size, path))
    entries.sort(key=lambda entry: entry[0])

    freed = 0
    now = time.time()
    total = sum(size for _, size, _ in entries)

    for last_used, size, path in entries:
        if _same_file_key(path) in protect:
            continue
        idle = now - last_used
        if grace and idle < grace:
            continue
        too_old = max_age and idle > max_age
        over_budget = budget and total > budget
        if not (too_old or over_budget or mode == "ephemeral"):
            continue
        try:
            path.unlink()
        except OSError:
            continue
        db.write("UPDATE tracks SET file=NULL WHERE file=?", (str(path),))
        total -= size
        freed += size
    return freed


def sweep_staging(max_age_hours: float = 1.0) -> int:
    """Delete download and render leftovers a crash or kill left behind."""
    removed = 0
    cutoff = time.time() - max_age_hours * 3600
    for path in AUDIO_DIR.glob("*"):
        if not path.name.startswith((RAW_PREFIX, STAGING_PREFIX)):
            continue
        try:
            if path.is_file() and path.stat().st_mtime < cutoff:
                path.unlink()
                removed += 1
        except OSError:
            continue
    return removed


def purge_all() -> None:
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    local_files = {Path(row['file']).resolve() for row in db.query(
        "SELECT file FROM tracks WHERE source='local' AND file IS NOT NULL")}
    for path in AUDIO_DIR.iterdir():
        if path.is_file() and path.resolve() not in local_files:
            path.unlink(missing_ok=True)
    db.write("UPDATE tracks SET file=NULL WHERE source IS NULL OR source != 'local'")
