"""Getting audio onto disk, at a consistent level, with its shape measured.

Pipeline per track:
    resolve  -> pick the best source match. Refuses live takes, music videos,
                karaoke, covers and pitched re-uploads; prefers the
                auto-generated upload of the actual release
    fetch    -> download bestaudio
    render   -> loudness-normalise to the configured LUFS, encode to opus
    analyse  -> parse the ebur128 loudness envelope to find where the track
                actually starts and where it winds down

That last step is what lets the hosts talk up the post: we know when the
music arrives, so we know when to stop speaking.

See NOTICE.md. Audio here is transient, local, personal, and never served
outside this machine.
"""
from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import threading
import time
import uuid
from pathlib import Path
from typing import Any

from . import analysis, config, db, sourceio, structure, versions

AUDIO_DIR = config.CACHE_DIR / "audio"
_RESOLVE_LOCK = threading.Lock()
_INFLIGHT: dict[str, threading.Event] = {}


def _log(*parts: Any) -> None:
    if config.DEBUG:
        print("[library]", *parts, flush=True)


# --------------------------------------------------------------------------
# Resolution
# --------------------------------------------------------------------------
# A performance, not the record. Parenthesised forms are the strong signals;
# a bare "live" is not, because plenty of songs are called Live Forever.
LIVE_MARKERS = (
    r"\(\s*live\b", r"\[\s*live\b", r"\blive\s*\)", r"[-–]\s*live\b",
    r"\blive (?:at|in|from|on|version|performance|video|session)\b",
    r"\bin concert\b", r"\bconcert\b", r"\bunplugged\b", r"\bacoustic session\b",
    r"\b(?:aol|abbey road|bbc|kexp|npr) sessions?\b", r"\btiny desk\b",
    r"\bboiler room\b", r"\b(?:dj|full) set\b", r"\bsetlist\b",
    r"\bfestival\b", r"\btour\b", r"\bencore\b", r"\bcrowd\b",
)

# A video, which routinely means an intro, an outro, or dialogue over the top.
# Weezer's Buddy Holly video runs 4:02 against a 2:40 record.
VIDEO_MARKERS = (
    r"\bofficial (?:music )?video\b", r"\bmusic video\b", r"\bofficial mv\b",
    r"\(\s*video\s*\)", r"\bvisuali[sz]er\b", r"\bshort film\b",
)

# Alternate editions require an explicit request when original preference is on.
VARIANT_WORDS = (
    "acoustic", "unplugged", "demo", "alternate version", "alternative version",
    "alt version", "alt. version", "reprise", "rework", "radio edit",
    "single version", "extended mix", "extended version", "mono mix",
    "re-recorded", "rerecorded", "taylor's version", "instrumental version",
    "orchestral version", "piano version", "stripped",
)

# Descriptions that give the game away even when the title is clean.
LIVE_IN_DESCRIPTION = (
    r"\blive (?:at|in|from|performance|recording)\b", r"\brecorded live\b",
    r"\bperformed live\b", r"\bin concert\b",
    r"\blive audio\b",
)
VIDEO_IN_DESCRIPTION = (
    r"\bofficial (?:music )?video\b", r"\bmusic video by\b",
)

# Auto-generated uploads of the actual release. The single most reliable
# marker of clean album audio, and worth more than anything in the title.
ART_TRACK = (r"provided to youtube by", r"auto-?generated by youtube")

# Re-encoded, pitched or "enhanced" uploads.
TAMPERED = (r"artificial intelligence", r"\bai (?:remaster|upscal)",
            r"\bspeed(?:ed)? up\b", r"\bpitched\b", r"\bbass boost")


def _matches(text: str, patterns: tuple[str, ...], wanted: str) -> str | None:
    """First pattern that hits the text but not the thing we asked for.

    The guard matters: searching for Oasis' Live Forever must not reject every
    result for containing the word live.
    """
    for pattern in patterns:
        if re.search(pattern, text) and not re.search(pattern, wanted):
            return pattern
    return None


def classify(entry: dict[str, Any], artist: str, title: str) -> dict[str, Any]:
    """What kind of upload is this? Used for both rejection and ranking."""
    name = (entry.get("title") or "").lower()
    channel = (entry.get("channel") or entry.get("uploader") or "").lower()
    description = (entry.get("description") or "").lower()[:600]
    # The guard string carries both shapes a result can take, because search
    # titles are written "Artist - Title". Without the dashed form, asking for
    # AC/DC's Live Wire matches the "- live" marker and every single candidate
    # is thrown away.
    wanted = f"{artist} - {title} | {artist} {title}".lower()
    haystack = f"{name} {description}"

    art_track = bool(_matches(haystack, ART_TRACK, "")
                     or channel.endswith(" - topic"))
    official_audio = bool(re.search(r"\bofficial audio\b", name))

    # The title outranks the description when they disagree. Label boilerplate
    # is frequently wrong: Sony's upload of Blue In Green is titled "(Official
    # Audio)" and described as "Official music video for...", and the title is
    # the one telling the truth.
    titled_video = bool(_matches(name, VIDEO_MARKERS, wanted))
    described_video = bool(_matches(description, VIDEO_IN_DESCRIPTION, wanted))
    clean, explicit = versions.source_edition(name, artist, title)

    return {
        "live": not versions._tagged(title, r"live(?:\s+(?:at|in|from)[^\])]+)?") and bool(_matches(name, LIVE_MARKERS, wanted)
                     or _matches(description, LIVE_IN_DESCRIPTION, wanted)
                     or (entry.get("live_status") or "") in
                     ("is_live", "was_live", "post_live")),
        "video": titled_video or (described_video and not
                                  (official_audio or art_track)),
        "art_track": art_track,
        "clean": clean,
        "explicit": explicit,
        "tampered": bool(_matches(haystack, TAMPERED, wanted)),
        "lyrics": bool(re.search(r"\blyrics?\b", name)),
        # Plain words rather than patterns, so asking for "Creep - Acoustic"
        # guards correctly against a result titled "Creep (Acoustic)". A
        # bracketed pattern would miss the dashed request entirely.
        "variant": any(word in name and word not in wanted
                       for word in VARIANT_WORDS) or any(
                           word not in wanted and re.search(r"\b" + word + r"\s+(?:version|performance|session|recording|take)\b", description)
                           for word in ("acoustic", "stripped", "unplugged")),
        "official_audio": bool(re.search(r"\bofficial audio\b", name)),
        "name": name, "channel": channel,
    }


def _candidate_score(entry: dict[str, Any], artist: str, title: str,
                     expected_ms: int, allow_video: bool = False
                     ) -> float | None:
    """Rank one search result. None means disqualified."""
    name = (entry.get("title") or "").lower()
    channel = (entry.get("channel") or entry.get("uploader") or "").lower()
    duration = entry.get("duration") or 0

    wanted = f"{artist} - {title} | {artist} {title}".lower()
    rejects = [str(k).lower() for k in
               (config.station.get("selection.reject_keywords") or [])]
    for word in rejects:
        # Only reject if the junk word isn't part of what we actually asked for.
        if word in name and word not in wanted:
            return None

    kind = classify(entry, artist, title)
    wants_clean = versions.is_clean_label(title)
    avoid_clean = config.station.get("selection.avoid_clean_versions", True)
    if avoid_clean and kind["clean"] and not wants_clean:
        return None
    if wants_clean and kind["explicit"]:
        return None
    if kind["live"] or kind["tampered"]:
        return None
    if kind["variant"] and config.station.get("selection.prefer_original_recording", True):
        return None
    if kind["video"] and not allow_video:
        return None

    if expected_ms and duration:
        tolerance = float(config.station.get("selection.duration_tolerance", 0.18) or 0.18)
        expected = expected_ms / 1000.0
        if abs(duration - expected) / expected > tolerance:
            return None
    if duration and (duration < 45 or duration > 900):
        return None

    score = 0.0
    if (avoid_clean and kind["explicit"]) or (wants_clean and kind["clean"]):
        score += 2.0
    # An auto-generated upload of the release itself beats everything. The
    # description marker is what actually catches these -- the "- Topic"
    # channel suffix is usually absent from search results.
    if kind["art_track"]:
        score += 6.0
    if kind["official_audio"]:
        score += 3.0
    if kind["video"]:
        score -= 4.0        # only reachable on the fallback pass
    if kind["lyrics"]:
        score -= 2.5        # often re-encoded, sometimes pitched
    if kind["variant"]:
        # A different take of the same song. Enough to lose to a plain
        # version, not enough to be unusable when it is all there is.
        score -= 7.0
    if db.norm(artist) and db.norm(artist) in db.norm(name + " " + channel):
        score += 2.0
    if db.norm(title) and db.norm(title) in db.norm(name):
        score += 2.0
    if entry.get("channel_is_verified"):
        score += 1.0
    if expected_ms and duration:
        drift = abs(duration - expected_ms / 1000.0)
        score += max(0.0, 2.0 - drift / 5.0)
    return score


def _same_recording(entry: dict[str, Any], artist: str, title: str) -> bool:
    name = entry.get('title') or ''
    name = re.sub(r'\s*[\[(](?:official(?: music)?(?: video| audio)?|audio|lyrics?|explicit|uncensored)[^\])]*[\])]',
                  '', name, flags=re.I).strip()
    parts = re.split(r'\s[-–—]\s', name, maxsplit=1)
    credit, song = parts if len(parts) == 2 else ('', name)
    primary = db.norm(db.primary_artist(artist))
    channel = db.norm(entry.get('channel') or entry.get('uploader') or '')
    channel = re.sub(r'\s*(?:official|vevo|topic)$', '', channel).strip()
    named_artist = not primary or primary == 'unknown' or (
        primary in db.norm(credit) if credit else channel in (primary, db.norm(artist)))
    return db.norm(song) == db.norm(title) and named_artist


def _source_info(video_id: str) -> dict[str, Any]:
    """Cache source labels separately from catalogue titles and user edits."""
    if not re.fullmatch(r"[A-Za-z0-9_-]{11}", video_id or ""):
        return {}
    path = config.CACHE_DIR / "source-info" / f"{video_id}.json"
    try:
        info = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(info, dict) and info.get("id") == video_id:
            return info
    except (OSError, ValueError):
        pass
    try:
        info = sourceio.describe(video_id)
        if isinstance(info, dict) and info.get("title"):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(info), encoding="utf-8")
            return info
    except (sourceio.SourceError, OSError):
        pass
    return {}


def resolve(artist: str, title: str, expected_ms: int = 0, *, exclude=()) -> str | None:
    """Return the best matching source video id, or None."""
    count = int(config.station.get("downloader.search_results", 5) or 5)
    query = f"ytsearch{count}:{artist} - {title}"
    options = {
        "quiet": True, "no_warnings": True, "skip_download": True,
        "extract_flat": "in_playlist", "socket_timeout": 15, "retries": 1,
        "default_search": "ytsearch",
    }
    info = sourceio.search(query, options)

    candidates = [e for e in ((info or {}).get("entries") or [])
                  if e and re.fullmatch(r"[\w-]{11}", e.get("id") or "")]

    # Prefer audio. If none survives, try an explicit-edition search before
    # allowing music videos. The censorship check applies to every pass.
    # The first refuses music videos outright, because a video is
    # routinely a different edit -- Weezer's Buddy Holly video runs 4:02
    # against a 2:40 record, all of it intro. The second allows them, so a
    # song that was only ever uploaded as a video is not lost entirely.
    # Live takes, karaoke and pitched re-uploads are refused on both.
    for attempt in range(3):
        allow_video = attempt == 2
        if attempt == 1:
            if (not config.station.get("selection.avoid_clean_versions", True)
                    or versions.is_clean_label(title)):
                continue
            try:
                extra = sourceio.search(query + " explicit audio", options)
                candidates.extend(e for e in ((extra or {}).get("entries") or [])
                                  if e and re.fullmatch(r"[\w-]{11}", e.get("id") or ""))
            except Exception as error:  # Keep the original video fallback usable.
                _log("explicit-edition search failed", artist, title, error)
        ranked = []
        require_identity = any(entry['id'] in exclude for entry in candidates)
        for entry in candidates:
            if entry['id'] in exclude:
                continue
            if require_identity:
                # A fallback must still identify this recording; a merely
                # high-ranked search result is not enough after the first fails.
                if (not _same_recording(entry, artist, title) or
                        classify(entry, artist, title)['variant']):
                    continue
            score = _candidate_score(entry, artist, title, expected_ms,
                                     allow_video=allow_video)
            if score is None:
                continue
            ranked.append((score, entry))

        for best in sorted(ranked, key=lambda candidate: -candidate[0]):
            entry = best[1]
            details = _source_info(entry["id"])
            checked = {**entry, **{k: v for k, v in details.items() if v is not None}}
            if _candidate_score(checked, artist, title, expected_ms, allow_video=allow_video) is None:
                continue
            entry = checked
            kind = classify(entry, artist, title)
            tags = [k for k in ("art_track", "official_audio", "video", "lyrics", "explicit", "clean")
                    if kind[k]]
            _log("resolved", artist, "-", title, "->", entry["id"],
                 f"(score {best[0]:.1f}"
                 + (f", {'+'.join(tags)}" if tags else "") + ")")
            if allow_video:
                _log("  only a video was available for", title)
            return entry["id"]

    _log("no acceptable match for", artist, "-", title,
         f"({len(candidates)} candidates rejected by source/version checks)")
    return None


# --------------------------------------------------------------------------
# Fetch + render
# --------------------------------------------------------------------------
def _ffmpeg(args: list[str], timeout: int = 300) -> subprocess.CompletedProcess:
    return subprocess.run(
        [config.FFMPEG, "-hide_banner", "-nostdin", "-y", *args],
        capture_output=True, text=True, timeout=timeout,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )


def _download_raw(video_id: str, destination: Path) -> Path | None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    # Console pulls and radio can fetch the same song in separate processes.
    # Each owns its staging files, including any .part file left on failure.
    destination = destination.with_name(destination.name + "_" + uuid.uuid4().hex)
    options = {
        "quiet": True, "no_warnings": True,
        "format": "bestaudio/best",
        "outtmpl": str(destination.with_suffix(".%(ext)s")),
        "socket_timeout": 20, "retries": 2,
        "noplaylist": True,
        "overwrites": True,
    }
    try:
        sourceio.download(video_id, options)
    except Exception:
        for part in destination.parent.glob(destination.name + ".*"):
            part.unlink(missing_ok=True)
        raise
    matches = sorted(destination.parent.glob(destination.stem + ".*"))
    return matches[0] if matches else None


def _unavailable(error: Exception) -> bool:
    """Only source-specific failures warrant trying a different upload."""
    message = str(error).lower()
    return any(phrase in message for phrase in (
        'please sign in', 'sign in to confirm', 'video unavailable',
        'video is unavailable', 'private video', 'video has been removed',
        'not available in your country', 'copyright', 'http error 403',
        'requested format is not available'))


def fetch_recording(artist: str, title: str, expected_ms: int = 0, *,
                    video_id: str | None = None, pinned: bool = False,
                    use_cache: bool = False, on_attempt=None) -> tuple[str, Path | None]:
    """Try up to three matching uploads; explicit video links stay pinned.

    Returns the chosen ID and raw audio, or the finished cache file on a hit.
    Timeouts and disk/encoding failures do not trigger another download.
    """
    if pinned and not video_id:
        raise sourceio.SourceError('The requested video link has no usable video ID.')
    excluded = {row['video_id'] for row in db.query(
        'SELECT video_id FROM unavailable_sources WHERE retry_after>?', (time.time(),))}
    attempted = set()
    last_error = None
    for attempt in range(1 if pinned else 3):
        if not video_id or (not pinned and video_id in excluded):
            video_id = resolve(artist, title, expected_ms, exclude=excluded | attempted)
        if not video_id or video_id in attempted:
            break
        attempted.add(video_id)
        if on_attempt:
            on_attempt(video_id, attempt)
        cached = _cache_path(video_id)
        if use_cache and cached.is_file():
            return video_id, cached
        try:
            raw = _download_raw(video_id, AUDIO_DIR / f'.raw_{video_id}')
            if raw:
                db.write('DELETE FROM unavailable_sources WHERE video_id=?', (video_id,))
            return video_id, raw
        except sourceio.SourceError as error:
            if pinned or not _unavailable(error):
                raise
            last_error = error
            excluded.add(video_id)
            db.write('INSERT OR REPLACE INTO unavailable_sources(video_id,retry_after,reason) VALUES(?,?,?)',
                     (video_id, time.time() + 86400, str(error)[:400]))
            _log('source unavailable; trying another matching upload', video_id)
            video_id = None
    if last_error:
        raise sourceio.SourceError('Matching uploads were unavailable. Try another video link or retry later. '
                                   + str(last_error)[:220]) from last_error
    return '', None


def _render(source: Path, target: Path, gain_db: float,
            fmt: str | None = None) -> bool:
    """Apply a single linear gain and encode to the working format.

    Deliberately NOT ffmpeg's one-pass `loudnorm`, which is a dynamic
    processor: it flattens a mastered record to about 1 LU of range, which
    kills the contrast that makes ducking and crossfades audible. Measuring
    first and applying one gain keeps the record's own dynamics intact.
    """
    rate = int(config.station.get("audio.sample_rate", 48000) or 48000)
    fmt = fmt or str(config.station.get("cache.format", "opus") or "opus")

    if fmt == "opus":
        codec = ["-c:a", "libopus", "-b:a",
                 str(config.station.get("cache.opus_bitrate", "160k") or "160k")]
    elif fmt == "flac":
        codec = ["-c:a", "flac", "-compression_level", "5"]
    elif fmt in ("m4a", "aac"):
        codec = ["-c:a", "aac", "-b:a",
                 str(config.station.get("cache.aac_bitrate", "192k") or "192k")]
    else:
        codec = ["-c:a", "pcm_s16le"]

    # A gentle limiter only catches the rare inter-sample overshoot; with the
    # gain already ceiling-limited it should almost never engage.
    chain = f"volume={gain_db:.2f}dB,alimiter=limit=0.97:level=disabled"

    result = _ffmpeg([
        "-i", str(source), "-vn", "-map_metadata", "-1",
        "-af", chain, "-ar", str(rate), "-ac", "2",
        *codec, str(target),
    ])
    if result.returncode != 0:
        _log("render failed", result.stderr[-500:])
        return False
    return target.exists() and target.stat().st_size > 1024


_FRAME = re.compile(r"t:\s*([\d.]+).*?\sS:\s*(-?[\d.]+|-inf)")
_INTEGRATED = re.compile(r"^\s*I:\s*(-?[\d.]+|-inf)\s*LUFS", re.MULTILINE)
_TRUE_PEAK = re.compile(r"Peak:\s*(-?[\d.]+|-inf)\s*dBFS")


def measure(path: Path) -> dict[str, Any]:
    """One ebur128 pass: integrated loudness, true peak, loudness envelope.

    The envelope is what tells us where a record actually starts. Where
    short-term loudness first climbs to within a few LU of the track's median
    and stays there is, in practice, the end of the intro -- the window a DJ
    talks over.
    """
    result = _ffmpeg(["-i", str(path), "-af", "ebur128=framelog=info:peak=true",
                      "-f", "null", "-"], timeout=240)
    stderr = result.stderr or ""

    samples: list[tuple[float, float]] = []
    for line in stderr.splitlines():
        match = _FRAME.search(line)
        if not match:
            continue
        try:
            moment = float(match.group(1))
            short_term = float(match.group(2))
        except ValueError:
            continue  # -inf during leading silence
        if short_term > -70:
            samples.append((moment, short_term))

    def _last(pattern: re.Pattern[str], default: float) -> float:
        found = pattern.findall(stderr)
        try:
            return float(found[-1]) if found else default
        except ValueError:
            return default

    return {
        "integrated": _last(_INTEGRATED, -23.0),
        "true_peak": _last(_TRUE_PEAK, -1.0),
        "samples": samples,
    }


def shape(samples: list[tuple[float, float]], duration: float) -> dict[str, float]:
    """Turn a loudness envelope into intro and outro points."""
    fallback = float(config.station.get("talk_placement.assumed_intro", 12.0) or 12.0)
    if len(samples) < 8:
        return {"intro_sec": fallback, "outro_sec": max(0.0, duration - 8.0)}

    values = sorted(value for _, value in samples)
    median = values[len(values) // 2]

    intro = _sustained_crossing(samples, median - 3.0, hold=1.5)
    intro = min(max(intro if intro is not None else fallback, 0.0), 45.0)

    outro = _last_crossing(samples, median - 6.0)
    if outro is None:
        outro = max(0.0, duration - 8.0)

    return {"intro_sec": intro, "outro_sec": outro}


def gain_for(integrated: float, true_peak: float) -> float:
    """Gain in dB to hit the target loudness without clipping."""
    target = float(config.station.get("audio.target_lufs", -14.0) or -14.0)
    ceiling = float(config.station.get("audio.true_peak_ceiling", -1.5) or -1.5)
    wanted = target - integrated
    headroom = ceiling - true_peak
    # Never push a track into the ceiling just to hit the loudness target.
    return max(-24.0, min(wanted, headroom, 24.0))


def _sustained_crossing(samples: list[tuple[float, float]], threshold: float,
                        hold: float) -> float | None:
    """First moment loudness goes above `threshold` and stays for `hold` sec."""
    start: float | None = None
    for moment, value in samples:
        if value >= threshold:
            if start is None:
                start = moment
            elif moment - start >= hold:
                return start
        else:
            start = None
    return None


def _last_crossing(samples: list[tuple[float, float]], threshold: float) -> float | None:
    for moment, value in reversed(samples):
        if value >= threshold:
            return moment
    return None


def _probe_duration(path: Path) -> float:
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "json", str(path)],
            capture_output=True, text=True, timeout=30,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
        return float(json.loads(result.stdout)["format"]["duration"])
    except Exception:  # noqa: BLE001
        return 0.0


# --------------------------------------------------------------------------
# Public entry point
# --------------------------------------------------------------------------
def _cache_path(video_id: str) -> Path:
    fmt = str(config.station.get("cache.format", "opus") or "opus")
    digest = hashlib.sha1(video_id.encode()).hexdigest()[:16]
    return AUDIO_DIR / f"{digest}.{fmt}"


def ensure(track: dict[str, Any]) -> dict[str, Any] | None:
    """Make sure this track is on disk, analysed, and ready to schedule.

    Blocking and slow on a cache miss -- always call this from the prefetch
    worker, never from the playout path.
    """
    key = track["key"]

    # Collapse duplicate requests for the same track into one download.
    with _RESOLVE_LOCK:
        event = _INFLIGHT.get(key)
        if event is None:
            event = threading.Event()
            _INFLIGHT[key] = event
            owner = True
        else:
            owner = False
    if not owner:
        event.wait(timeout=180)
        row = db.one("SELECT * FROM tracks WHERE key=?", (key,))
        if not row or not row["file"]:
            return None
        ready = dict(row)
        ready["structure"] = structure.profile_for(ready)
        return ready

    try:
        ready = _ensure_locked(track)
        if ready and ready.get("file"):
            # This prefetch worker is the only place that decodes for cue
            # analysis; timeline construction reads the prepared cache only.
            ready["structure"] = structure.profile(ready["file"])
        return ready
    finally:
        with _RESOLVE_LOCK:
            _INFLIGHT.pop(key, None)
        event.set()


def _ensure_locked(track: dict[str, Any]) -> dict[str, Any] | None:
    key = track["key"]
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)

    existing = db.one("SELECT * FROM tracks WHERE key=?", (key,))
    if existing and db.field(existing, "source_url"):
        from . import youtube
        track = youtube.hydrate(dict(existing))
        existing = track
    use_existing = True
    if (existing and existing["file"] and existing["video_id"]
            and db.field(existing, "source") != "local" and not db.field(existing, "source_url")
            and config.station.get("selection.prefer_original_recording", True)):
        info = _source_info(existing["video_id"])
        if info and _candidate_score(info, track["artist"], track["title"],
                                     track.get("expected_ms") or 0, allow_video=True) is None:
            use_existing = False
            _log("replacing alternate cached recording for", track["artist"], track["title"])
    if existing and existing["file"] and use_existing:
        path = Path(existing["file"])
        if path.exists():
            # Upgrade genre/embedded lyric evidence on the one track being
            # prepared, without rescanning the user's library or redoing DSP.
            from . import importer
            existing = importer.refresh_tags(dict(existing), path)
            # A file cached before tempo and key analysis existed would
            # otherwise never get it, because this early return skips the
            # whole pipeline. Fill the gap in place.
            if not db.field(existing, "bpm"):
                tonal = analysis.profile(path)
                db.write(
                    "UPDATE tracks SET bpm=?, bpm_confidence=?, key_tonic=?, "
                    "key_mode=?, key_confidence=?, camelot=?, beat_offset=?, "
                    "beat_period=?, beat_residual_ms=?, downbeat_offset=? WHERE key=?",
                    (tonal["bpm"], tonal["bpm_confidence"], tonal["key_tonic"],
                     tonal["key_mode"], tonal["key_confidence"],
                     tonal["camelot"], tonal["beat_offset"],
                     tonal["beat_period"], tonal["beat_residual_ms"],
                     tonal["downbeat_offset"], key))
                _log("backfilled analysis for", track.get("title"),
                     f"{tonal['bpm']:.0f}bpm {tonal['camelot'] or '?'}")
                existing = db.one("SELECT * FROM tracks WHERE key=?", (key,))
            return dict(existing)

    if existing and db.field(existing, "source") == "local":
        return None

    # A saved ID without usable audio may predate the edition preference.
    # Re-resolve it under the current rules instead of downloading it blindly.
    saved_id = existing["video_id"] if existing else None
    if (not db.field(existing, "source_url")
            and (config.station.get("selection.avoid_clean_versions", True)
                 or config.station.get("selection.prefer_original_recording", True))):
        saved_id = None
    video_id, raw = fetch_recording(
        track['artist'], track['title'], track.get('expected_ms') or 0,
        video_id=saved_id, pinned=bool(db.field(existing, 'source_url')), use_cache=True)
    if not video_id:
        db.write("UPDATE tracks SET blocked=1 WHERE key=?", (key,))
        return None
    db.write("UPDATE tracks SET video_id=? WHERE key=?", (video_id, key))

    final = _cache_path(video_id)
    measured: dict[str, Any] | None = None
    if raw and raw != final and final.exists():
        raw.unlink(missing_ok=True)

    if not final.exists():
        if not raw:
            return None

        # Measure the source, then apply one gain. Analysing the raw file also
        # gets us the shape for free -- a linear gain does not move it.
        measured = measure(raw)
        gain = gain_for(measured["integrated"], measured["true_peak"])
        ok = _render(raw, final, gain)
        try:
            raw.unlink()
        except OSError:
            pass
        if not ok:
            return None
        _log(f"normalised {measured['integrated']:.1f} LUFS "
             f"-> {measured['integrated'] + gain:.1f} ({gain:+.1f} dB)")

    if measured is None:  # cache hit on the audio, but no stored shape
        measured = measure(final)

    duration = _probe_duration(final)
    stats = shape(measured["samples"], duration)

    # Tempo and key, so the director can pick a transition that suits the two
    # records rather than always reaching for the same crossfade.
    tonal = analysis.profile(final)

    db.write(
        "UPDATE tracks SET blocked=0, file=?, duration=?, intro_sec=?, outro_sec=?, "
        "lufs=?, bpm=?, bpm_confidence=?, key_tonic=?, key_mode=?, "
        "key_confidence=?, camelot=?, beat_offset=?, beat_period=?, "
        "beat_residual_ms=?, downbeat_offset=? WHERE key=?",
        (str(final), duration, stats["intro_sec"], stats["outro_sec"],
         measured["integrated"], tonal["bpm"], tonal["bpm_confidence"],
         tonal["key_tonic"], tonal["key_mode"], tonal["key_confidence"],
         tonal["camelot"], tonal["beat_offset"], tonal["beat_period"],
         tonal["beat_residual_ms"], tonal["downbeat_offset"], key),
    )
    _log("ready", track["artist"], "-", track["title"],
         f"{duration:.0f}s intro={stats['intro_sec']:.1f}s "
         f"outro={stats['outro_sec']:.1f}s "
         f"{tonal['bpm']:.0f}bpm {tonal['camelot'] or '?'}")
    row = db.one("SELECT * FROM tracks WHERE key=?", (key,))
    return dict(row) if row else None


# --------------------------------------------------------------------------
# Cache housekeeping
# --------------------------------------------------------------------------
def evict(protect: set[str] | None = None) -> int:
    """Enforce the cache budget. Returns bytes freed."""
    protect = {str(Path(p)) for p in (protect or set())}
    protect.update(row['file'] for row in db.query(
        "SELECT file FROM tracks WHERE source='local' AND file IS NOT NULL"))
    mode = str(config.station.get("cache.mode", "lru") or "lru")
    max_age = float(config.station.get("cache.max_age_hours", 168) or 0) * 3600
    budget = float(config.station.get("cache.max_size_gb", 6.0) or 0) * 1024**3

    files = [p for p in AUDIO_DIR.glob("*") if p.is_file()
             and not p.name.startswith(".raw_")]
    files.sort(key=lambda p: p.stat().st_atime)

    freed = 0
    now = time.time()
    total = sum(p.stat().st_size for p in files)

    for path in files:
        if str(path) in protect:
            continue
        too_old = max_age and (now - path.stat().st_mtime) > max_age
        over_budget = budget and total > budget
        if not (too_old or over_budget or mode == "ephemeral"):
            continue
        size = path.stat().st_size
        try:
            path.unlink()
        except OSError:
            continue
        db.write("UPDATE tracks SET file=NULL WHERE file=?", (str(path),))
        total -= size
        freed += size
    return freed


def purge_all() -> None:
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    local_files = {Path(row['file']).resolve() for row in db.query(
        "SELECT file FROM tracks WHERE source='local' AND file IS NOT NULL")}
    for path in AUDIO_DIR.iterdir():
        if path.is_file() and path.resolve() not in local_files:
            path.unlink(missing_ok=True)
    db.write("UPDATE tracks SET file=NULL WHERE source IS NULL OR source != 'local'")
